struct cpuinfo_mock_file filesystem[] = {
	{
		.path = "/proc/cpuinfo",
		.size = 335,
		.content =
			"Processor\t: ARMv7 Processor rev 4 (v7l)\n"
			"processor\t: 0\n"
			"BogoMIPS\t: 13.53\n"
			"\n"
			"processor\t: 1\n"
			"BogoMIPS\t: 13.53\n"
			"\n"
			"Features\t: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 \n"
			"CPU implementer\t: 0x51\n"
			"CPU architecture: 7\n"
			"CPU variant\t: 0x1\n"
			"CPU part\t: 0x04d\n"
			"CPU revision\t: 4\n"
			"\n"
			"Hardware\t: SAMSUNG M2_ATT\n"
			"Revision\t: 0010\n"
			"Serial\t\t: 0000eb0d0000f3a2\n",
	},
	{
		.path = "/system/build.prop",
		.size = 5377,
		.content =
			"# begin build properties\n"
			"# autogenerated by buildinfo.sh\n"
			"ro.build.id=JRO03L\n"
			"ro.build.display.id=JRO03L.I747UCDLK3\n"
			"ro.build.version.incremental=I747UCDLK3\n"
			"ro.build.version.sdk=16\n"
			"ro.build.version.codename=REL\n"
			"ro.build.version.release=4.1.1\n"
			"ro.build.date=Thu Nov 15 15:56:47 KST 2012\n"
			"ro.build.date.utc=1352962607\n"
			"ro.build.type=user\n"
			"ro.build.user=se.infra\n"
			"ro.build.host=SEP-103\n"
			"ro.build.tags=release-keys\n"
			"ro.product.model=SAMSUNG-SGH-I747\n"
			"ro.product.brand=samsung\n"
			"ro.product.name=d2uc\n"
			"ro.product.device=d2att\n"
			"ro.product.board=MSM8960\n"
			"ro.chipname=MSM8960\n"
			"ro.product.cpu.abi=armeabi-v7a\n"
			"ro.product.cpu.abi2=armeabi\n"
			"ro.product_ship=true\n"
			"ro.product.manufacturer=samsung\n"
			"ro.product.locale.language=en\n"
			"ro.product.locale.region=GB\n"
			"ro.wifi.channels=\n"
			"ro.board.platform=msm8960\n"
			"# ro.build.product is obsolete; use ro.product.device\n"
			"ro.build.product=d2att\n"
			"# Do not try to parse ro.build.description or .fingerprint\n"
			"ro.build.description=d2uc-user 4.1.1 JRO03L I747UCDLK3 release-keys\n"
			"ro.build.fingerprint=samsung/d2uc/d2att:4.1.1/JRO03L/I747UCDLK3:user/release-keys\n"
			"ro.build.characteristics=att\n"
			"# Samsung Specific Properties\n"
			"ro.build.PDA=I747UCDLK3\n"
			"ro.build.hidden_ver=I747UCDLK3\n"
			"ro.build.changelist=274808\n"
			"# end build properties\n"
			"#\n"
			"# system.prop for surf\n"
			"#\n"
			"\n"
			"rild.libpath=/system/lib/libril-qc-qmi-1.so\n"
			"rild.libargs=-d /dev/smd0\n"
			"persist.rild.nitz_plmn=\n"
			"persist.rild.nitz_long_ons_0=\n"
			"persist.rild.nitz_long_ons_1=\n"
			"persist.rild.nitz_long_ons_2=\n"
			"persist.rild.nitz_long_ons_3=\n"
			"persist.rild.nitz_short_ons_0=\n"
			"persist.rild.nitz_short_ons_1=\n"
			"persist.rild.nitz_short_ons_2=\n"
			"persist.rild.nitz_short_ons_3=\n"
			"ril.subscription.types=NV,RUIM\n"
			"DEVICE_PROVISIONED=1\n"
			"debug.sf.hw=1\n"
			"debug.egl.hw=1\n"
			"debug.composition.type=dyn\n"
			"debug.compbypass.enable=1\n"
			"debug.hwui.render_dirty_regions=true\n"
			"dalvik.vm.heapsize=36m\n"
			"debug.enable.wl_log=1\n"
			"debug.mdpcomp.maxlayer=3\n"
			"\n"
			"#\n"
			"# system props for the cne module\n"
			"#\n"
			"persist.cne.bat.range.low.med=30\n"
			"persist.cne.bat.range.med.high=60\n"
			"persist.cne.loc.policy.op=/system/etc/OperatorPolicy.xml\n"
			"persist.cne.loc.policy.user=/system/etc/UserPolicy.xml\n"
			"persist.cne.bwbased.rat.sel=false\n"
			"persist.cne.snsr.based.rat.mgt=false\n"
			"persist.cne.bat.based.rat.mgt=false\n"
			"persist.cne.rat.acq.time.out=30000\n"
			"persist.cne.rat.acq.retry.tout=0\n"
			"persist.cne.feature=0\n"
			"\n"
			"ro.hdmi.enable=true\n"
			"lpa.decode=true\n"
			"lpa.use-stagefright=true\n"
			"\n"
			"#system props for the MM modules\n"
			"\n"
			"media.stagefright.enable-player=true\n"
			"media.stagefright.enable-http=true\n"
			"media.stagefright.enable-aac=true\n"
			"media.stagefright.enable-qcp=true\n"
			"media.stagefright.enable-fma2dp=true\n"
			"media.stagefright.enable-scan=true\n"
			"mmp.enable.3g2=true\n"
			"\n"
			"#\n"
			"# system props for the data modules\n"
			"#\n"
			"ro.use_data_netmgrd=true\n"
			"\n"
			"#system props for time-services\n"
			"persist.timed.enable=true\n"
			"\n"
			"# System props for audio\n"
			"persist.audio.fluence.mode=endfire\n"
			"persist.audio.vr.enable=false\n"
			"persist.audio.handset.mic=digital\n"
			"\n"
			"# System prop to select audio resampler quality\n"
			"af.resampler.quality=255\n"
			"# System prop to select MPQAudioPlayer by default on mpq8064\n"
			"mpq.audio.decode=true\n"
			"\n"
			"#\n"
			"# system prop for opengles version\n"
			"#\n"
			"# 131072 is decimal for 0x20000 to report version 2\n"
			"ro.opengles.version=131072\n"
			"\n"
			"#\n"
			"# system property for Bluetooth Handsfree Profile version\n"
			"#\n"
			"ro.bluetooth.hfp.ver=1.6\n"
			"#\n"
			"#system prop for Bluetooth hci transport\n"
			"ro.qualcomm.bt.hci_transport=smd\n"
			"#\n"
			"# system prop for requesting Master role in incoming Bluetooth connection.\n"
			"#\n"
			"ro.bluetooth.request.master=true\n"
			"#\n"
			"# system prop for Bluetooth Auto connect for remote initated connections\n"
			"#\n"
			"ro.bluetooth.remote.autoconnect=true\n"
			"# system property for Bluetooth discoverability time out in seconds\n"
			"# 0: Always discoverable\n"
			"#debug.bt.discoverable_time=0\n"
			"\n"
			"#system prop for switching gps driver to qmi\n"
			"persist.gps.qmienabled=true\n"
			"\n"
			"# System property for cabl\n"
			"ro.qualcomm.cabl=1\n"
			"\n"
			"#\n"
			"# System prop for sending transmit power request to RIL during WiFi hotspot on/off\n"
			"#\n"
			"ro.ril.transmitpower=true\n"
			"\n"
			"#\n"
			"#Simulate sdcard on /data/media\n"
			"#\n"
			"persist.fuse_sdcard=true\n"
			"ro.hwui.text_cache_width=2048\n"
			"\n"
			"#\n"
			"# Supports warmboot capabilities\n"
			"#\n"
			"ro.warmboot.capability=1\n"
			"\n"
			"ro.sf.lcd_density=320\n"
			"\n"
			"# Keep SIM state on LPM mode\n"
			"persist.radio.apm_sim_not_pwdn=1\n"
			"\n"
			"# System property for Default touch key light duration\n"
			"ro.button_key_light=6000\n"
			"\n"
			"# System proverty for sys info indication\n"
			"persist.radio.add_power_save=1\n"
			"\n"
			"# System property for HDMI/WFD\n"
			"persist.sys.camera.connect=0\n"
			"persist.sys.camera.transform=0\n"
			"persist.sys.videomode=0\n"
			"#\n"
			"# ADDITIONAL_BUILD_PROPERTIES\n"
			"#\n"
			"ro.vendor.extension_library=/system/lib/libqc-opt.so\n"
			"ro.error.receiver.default=com.samsung.receiver.error\n"
			"dalvik.vm.heapstartsize=8m\n"
			"dalvik.vm.heapgrowthlimit=64m\n"
			"dalvik.vm.heapsize=256m\n"
			"dalvik.vm.heaputilization=0.25\n"
			"dalvik.vm.heapidealfree=8388608\n"
			"dalvik.vm.heapconcurrentstart=2097152\n"
			"ro.hdcp2.rx=tz\n"
			"ro.sec.fle.encryption=true\n"
			"ro.config.alarm_alert=Walk_in_the_forest.ogg\n"
			"ro.config.ringtone=ATT_Firefly_Default.ogg\n"
			"ro.config.notification_sound=S_Whistle.ogg\n"
			"ro.monkey=0\n"
			"keyguard.no_require_sim=true\n"
			"ro.com.android.dateformat=MM-dd-yyyy\n"
			"ro.carrier=unknown\n"
			"ro.ril.hsxpa=1\n"
			"ro.ril.gprsclass=10\n"
			"ro.adb.qemud=1\n"
			"ro.setupwizard.mode=OPTIONAL\n"
			"ro.com.google.apphider=off\n"
			"ro.com.google.clientidbase=android-samsung\n"
			"ro.com.google.clientidbase.ms=android-att-us\n"
			"ro.com.google.clientidbase.am=android-att-us\n"
			"ro.com.google.clientidbase.yt=android-samsung\n"
			"ro.com.google.clientidbase.gmm=android-samsung\n"
			"ro.com.google.gmsversion=4.1_r3\n"
			"net.bt.name=Android\n"
			"dalvik.vm.stack-trace-file=/data/anr/traces.txt\n"
			"\n",
	},
	{
		.path = "/sys/devices/system/cpu/kernel_max",
		.size = 2,
		.content = "1\n",
	},
	{
		.path = "/sys/devices/system/cpu/possible",
		.size = 4,
		.content = "0-1\n",
	},
	{
		.path = "/sys/devices/system/cpu/present",
		.size = 4,
		.content = "0-1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq",
		.size = 8,
		.content = "1512000\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq",
		.size = 7,
		.content = "384000\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/physical_package_id",
		.size = 3,
		.content = "-1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/core_siblings_list",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/core_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/thread_siblings_list",
		.size = 2,
		.content = "0\n",
	},
	{ NULL },
};
