struct cpuinfo_mock_file filesystem[] = {
	{
		.path = "/proc/cpuinfo",
		.size = 1121,
		.content =
			"Processor\t: ARMv7 Processor rev 5 (v7l)\n"
			"processor\t: 0\n"
			"model name\t: ARMv7 Processor rev 5 (v7l)\n"
			"BogoMIPS\t: 2603.41\n"
			"Features\t: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 \n"
			"CPU implementer\t: 0x41\n"
			"CPU architecture: 7\n"
			"CPU variant\t: 0x0\n"
			"CPU part\t: 0xc07\n"
			"CPU revision\t: 5\n"
			"\n"
			"processor\t: 1\n"
			"model name\t: ARMv7 Processor rev 5 (v7l)\n"
			"BogoMIPS\t: 2609.97\n"
			"Features\t: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 \n"
			"CPU implementer\t: 0x41\n"
			"CPU architecture: 7\n"
			"CPU variant\t: 0x0\n"
			"CPU part\t: 0xc07\n"
			"CPU revision\t: 5\n"
			"\n"
			"processor\t: 2\n"
			"model name\t: ARMv7 Processor rev 5 (v7l)\n"
			"BogoMIPS\t: 2609.97\n"
			"Features\t: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 \n"
			"CPU implementer\t: 0x41\n"
			"CPU architecture: 7\n"
			"CPU variant\t: 0x0\n"
			"CPU part\t: 0xc07\n"
			"CPU revision\t: 5\n"
			"\n"
			"processor\t: 3\n"
			"model name\t: ARMv7 Processor rev 5 (v7l)\n"
			"BogoMIPS\t: 2609.97\n"
			"Features\t: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 \n"
			"CPU implementer\t: 0x41\n"
			"CPU architecture: 7\n"
			"CPU variant\t: 0x0\n"
			"CPU part\t: 0xc07\n"
			"CPU revision\t: 5\n"
			"\n"
			"Hardware\t: sc8830\n"
			"Revision\t: 0004\n"
			"Serial\t\t: 4200ddccd2da6300\n",
	},
	{
		.path = "/system/build.prop",
		.size = 5350,
		.content =
			"\n"
			"# begin build properties\n"
			"# autogenerated by buildinfo.sh\n"
			"ro.build.id=LMY48B\n"
			"ro.build.display.id=LMY48B.G531HUBU0APE2\n"
			"ro.build.version.incremental=G531HUBU0APE2\n"
			"ro.build.version.sdk=22\n"
			"ro.build.version.codename=REL\n"
			"ro.build.version.all_codenames=REL\n"
			"ro.build.version.release=5.1.1\n"
			"ro.build.version.security_patch=2016-06-01\n"
			"ro.build.version.base_os=\n"
			"ro.build.date=Tue May 31 14:49:04 KST 2016\n"
			"ro.build.date.utc=1464673744\n"
			"ro.build.type=user\n"
			"ro.build.user=dpi\n"
			"ro.build.host=SWHC3703\n"
			"ro.build.tags=release-keys\n"
			"ro.build.flavor=grandprimeve3gub-user\n"
			"ro.product.model=SM-G531H\n"
			"ro.product.brand=samsung\n"
			"ro.product.name=grandprimeve3gub\n"
			"ro.product.device=grandprimeve3g\n"
			"ro.product.board=SC7730SE\n"
			"# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,\n"
			"# use ro.product.cpu.abilist instead.\n"
			"ro.product.cpu.abi=armeabi-v7a\n"
			"ro.product.cpu.abi2=armeabi\n"
			"ro.product.cpu.abilist=armeabi-v7a,armeabi\n"
			"ro.product.cpu.abilist32=armeabi-v7a,armeabi\n"
			"ro.product.cpu.abilist64=\n"
			"ro.product.manufacturer=samsung\n"
			"ro.product.locale.language=en\n"
			"ro.product.locale.region=US\n"
			"ro.wifi.channels=\n"
			"ro.board.platform=sc8830\n"
			"# ro.build.product is obsolete; use ro.product.device\n"
			"ro.build.product=grandprimeve3g\n"
			"# Do not try to parse description, fingerprint, or thumbprint\n"
			"ro.build.description=grandprimeve3gub-user 5.1.1 LMY48B G531HUBU0APE2 release-keys\n"
			"ro.build.fingerprint=samsung/grandprimeve3gub/grandprimeve3g:5.1.1/LMY48B/G531HUBU0APE2:user/release-keys\n"
			"ro.build.characteristics=default\n"
			"# Samsung Specific Properties\n"
			"ro.build.PDA=G531HUBU0APE2\n"
			"ro.build.hidden_ver=G531HUBU0APE2\n"
			"ro.config.rm_preload_enabled=0\n"
			"ro.build.changelist=1045439\n"
			"ro.product_ship=true\n"
			"ro.chipname=SC7730SE\n"
			"# end build properties\n"
			"#\n"
			"# from device/samsung/grandprimeve3g/system.prop\n"
			"#\n"
			"\n"
			"ro.sf.lcd_density=240\n"
			"ro.sf.lcd_width=154\n"
			"ro.sf.lcd_height=90\n"
			"ro.opengles.version=131072\n"
			"ro.product.hardware=TSHARK2TABE_V1.0.0\n"
			"\n"
			"debug.hwui.render_dirty_regions=false\n"
			"\n"
			"# Bluetooth OPP low speed for save power\n"
			"debug.bt.lowspeed=true\n"
			"\n"
			"persist.ttydev=ttyVUART0\n"
			"\n"
			"# delay for ConnectivityChange broadcast (ms)\n"
			"conn.connectivity_change_delay = 0\n"
			"\n"
			"ro.product.partitionpath=/dev/block/platform/sdio_emmc/by-name/\n"
			"\n"
			"# Default ecclist\n"
			"ro.ril.ecclist=112,911,#911,*911\n"
			"\n"
			"persist.modem.w.enable=1\n"
			"persist.modem.w.nvp=w\n"
			"ro.modem.w.dev=/proc/cpw/\n"
			"ro.modem.w.tty=/dev/stty_w\n"
			"ro.modem.w.eth=rmnet\n"
			"ro.modem.w.snd=1\n"
			"ro.modem.w.diag=/dev/slog_w\n"
			"ro.modem.w.loop=/dev/spipe_w0\n"
			"ro.modem.w.nv=/dev/spipe_w1\n"
			"ro.modem.w.assert=/dev/spipe_w2\n"
			"ro.modem.w.vbc=/dev/spipe_w6\n"
			"ro.modem.w.id=0\n"
			"ro.modem.w.fixnv_size=0x40000\n"
			"ro.modem.w.runnv_size=0x60000\n"
			"\n"
			"ro.modem.wcn.enable=1\n"
			"ro.modem.wcn.dev=/dev/cpwcn\n"
			"ro.modem.wcn.tty=/deiv/stty_wcn\n"
			"ro.modem.wcn.diag=/dev/slog_wcn\n"
			"ro.modem.wcn.assert=/dev/spipe_wcn2\n"
			"ro.modem.wcn.id=1\n"
			"ro.modem.wcn.count=1\n"
			"ro.digital.fm.support=1\n"
			"\n"
			"persist.sys.engpc.disable=0\n"
			"\n"
			"ro.config.ksm.support=true\n"
			"\n"
			"#zram config\n"
			"#ro.config.zram.support=true\n"
			"#ro.board_ram_size=mid\n"
			"\n"
			"# SPRD: add low cost low memory\n"
			"ro.config.low_ram=true\n"
			"\n"
			"#if our product not support drm,set as false\n"
			"drm.service.enabled=true\n"
			"\n"
			"# hotspot development\n"
			"ro.hotspot.enabled=1\n"
			"\n"
			"# this product does not support bt and softap coexist\n"
			"ro.btwifisoftap.coexist=false\n"
			"# SPRD: add support hwrotation\n"
			"ro.sf.hwrotation=0\n"
			"\n"
			"# System property for storage_preload\n"
			"persist.sys.storage_preload=1\n"
			"\n"
			"# SAMP_SPCM\n"
			"sys.config.samp_spcm_enable=true\n"
			"sys.config.spcm_db_enable=true\n"
			"sys.config.spcm_db_launcher=true\n"
			"sys.config.spcm_preload_enable=true\n"
			"\n"
			"#\n"
			"# ADDITIONAL_BUILD_PROPERTIES\n"
			"#\n"
			"ro.com.android.dateformat=MM-dd-yyyy\n"
			"ro.carrier=unknown\n"
			"ro.com.google.clientidbase=android-samsung\n"
			"ro.security.icd.flagmode=single\n"
			"drm.service.enabled=true\n"
			"ro.modem.wcn.enable=1\n"
			"ro.modem.wcn.dev=/dev/cpwcn\n"
			"ro.modem.wcn.tty=/deiv/stty_wcn\n"
			"ro.modem.wcn.diag=/dev/slog_wcn\n"
			"ro.modem.wcn.assert=/dev/spipe_wcn2\n"
			"ro.modem.wcn.id=1\n"
			"ro.modem.wcn.count=1\n"
			"camera.disable_zsl_mode=1\n"
			"ro.digital.fm.support=1\n"
			"persist.sys.sprd.modemreset=1\n"
			"ro.adb.secure=1\n"
			"persist.sys.sprd.wcnreset=1\n"
			"ro.storage.flash_type=2\n"
			"persist.storage.type=2\n"
			"sys.tempsd.enable=0\n"
			"sys.internal.emulated=1\n"
			"ro.storage.install2internal=0\n"
			"keyguard.no_require_sim=true\n"
			"ro.com.android.dataroaming=false\n"
			"ro.msms.phone_count=2\n"
			"persist.msms.phone_count=2\n"
			"persist.msms.phone_default=0\n"
			"ro.modem.w.count=2\n"
			"persist.sys.modem.diag=,gser\n"
			"sys.usb.gser.count=4\n"
			"lmk.autocalc=false\n"
			"dalvik.vm.heapstartsize=8m\n"
			"dalvik.vm.heapgrowthlimit=96m\n"
			"dalvik.vm.heapsize=256m\n"
			"dalvik.vm.heaptargetutilization=0.75\n"
			"dalvik.vm.heapminfree=2m\n"
			"dalvik.vm.heapmaxfree=8m\n"
			"ro.build.scafe=americano\n"
			"ro.build.scafe.size=short\n"
			"ro.build.scafe.cream=white\n"
			"ro.build.scafe.shot=single\n"
			"ro.sec.fle.encryption=true\n"
			"ro.error.receiver.default=com.samsung.receiver.error\n"
			"sys.config.samp_ppm_enable=false\n"
			"ro.config.oomminfree=49152,61440,73728,86016,98304,122880\n"
			"ro.config.sdha_default_margin=25\n"
			"ro.config.is_lowend_samp=true\n"
			"ro.multisim.simslotcount=2\n"
			"ro.config.ringtone_2=Basic_Bell.ogg\n"
			"ro.config.notification_sound_2=S_Charming_Bell.ogg\n"
			"ro.config.ringtone=Over_the_horizon.ogg\n"
			"ro.config.notification_sound=S_Whistle.ogg\n"
			"ro.config.alarm_alert=Morning_flower.ogg\n"
			"ro.config.media_sound=Media_preview_Touch_the_light.ogg\n"
			"ro.frp.pst=/dev/block/persistent\n"
			"ro.com.google.gmsversion=5.1_r3\n"
			"ro.setupwizard.mode=DISABLED\n"
			"persist.sys.dalvik.vm.lib.2=libart.so\n"
			"dalvik.vm.isa.arm.features=div\n"
			"ro.build.selinux=1\n"
			"ro.config.knox=v00\n"
			"ro.kernel.qemu=0\n"
			"net.bt.name=Android\n"
			"dalvik.vm.stack-trace-file=/data/anr/traces.txt\n"
			"\n",
	},
	{
		.path = "/sys/devices/system/cpu/kernel_max",
		.size = 2,
		.content = "3\n",
	},
	{
		.path = "/sys/devices/system/cpu/possible",
		.size = 4,
		.content = "0-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/present",
		.size = 4,
		.content = "0-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq",
		.size = 8,
		.content = "1300000\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq",
		.size = 7,
		.content = "768000\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/physical_package_id",
		.size = 3,
		.content = "15\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/core_siblings_list",
		.size = 4,
		.content = "0-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/core_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/thread_siblings_list",
		.size = 2,
		.content = "0\n",
	},
	{ NULL },
};
