struct cpuinfo_mock_file filesystem[] = {
	{
		.path = "/proc/cpuinfo",
		.size = 419,
		.content =
			"Processor\t: ARMv7 Processor rev 1 (v7l)\n"
			"processor\t: 0\n"
			"BogoMIPS\t: 38.40\n"
			"\n"
			"processor\t: 1\n"
			"BogoMIPS\t: 38.40\n"
			"\n"
			"processor\t: 2\n"
			"BogoMIPS\t: 38.40\n"
			"\n"
			"processor\t: 3\n"
			"BogoMIPS\t: 38.40\n"
			"\n"
			"Features\t: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt \n"
			"CPU implementer\t: 0x51\n"
			"CPU architecture: 7\n"
			"CPU variant\t: 0x2\n"
			"CPU part\t: 0x06f\n"
			"CPU revision\t: 1\n"
			"\n"
			"Hardware\t: Qualcomm MSM8974PRO-AC\n"
			"Revision\t: 000e\n"
			"Serial\t\t: 0000cec2000097e3\n",
	},
	{
		.path = "/system/build.prop",
		.size = 7266,
		.content =
			"\n"
			"# begin build properties\n"
			"# autogenerated by buildinfo.sh\n"
			"ro.build.id=LMY47X\n"
			"ro.build.display.id=LMY47X.G900AUCU4CPA1\n"
			"ro.build.version.incremental=G900AUCU4CPA1\n"
			"ro.build.version.sdk=22\n"
			"ro.build.version.codename=REL\n"
			"ro.build.version.all_codenames=REL\n"
			"ro.build.version.release=5.1.1\n"
			"ro.build.version.security_patch=2016-02-01\n"
			"ro.build.version.base_os=\n"
			"ro.build.date=Wed Jan 27 21:23:36 KST 2016\n"
			"ro.build.date.utc=1453897416\n"
			"ro.build.type=user\n"
			"ro.build.user=dpi\n"
			"ro.build.host=SWHC3812\n"
			"ro.build.tags=release-keys\n"
			"ro.build.flavor=klteuc-user\n"
			"ro.product.model=SAMSUNG-SM-G900A\n"
			"ro.product.brand=samsung\n"
			"ro.product.name=klteuc\n"
			"ro.product.device=klteatt\n"
			"ro.product.board=MSM8974\n"
			"# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,\n"
			"# use ro.product.cpu.abilist instead.\n"
			"ro.product.cpu.abi=armeabi-v7a\n"
			"ro.product.cpu.abi2=armeabi\n"
			"ro.product.cpu.abilist=armeabi-v7a,armeabi\n"
			"ro.product.cpu.abilist32=armeabi-v7a,armeabi\n"
			"ro.product.cpu.abilist64=\n"
			"ro.product.manufacturer=samsung\n"
			"ro.product.locale.language=en\n"
			"ro.product.locale.region=US\n"
			"ro.wifi.channels=\n"
			"ro.board.platform=msm8974\n"
			"# ro.build.product is obsolete; use ro.product.device\n"
			"ro.build.product=klteatt\n"
			"# Do not try to parse description, fingerprint, or thumbprint\n"
			"ro.build.description=klteuc-user 5.1.1 LMY47X G900AUCU4CPA1 release-keys\n"
			"ro.build.fingerprint=samsung/klteuc/klteatt:5.1.1/LMY47X/G900AUCU4CPA1:user/release-keys\n"
			"ro.build.characteristics=att\n"
			"# Samsung Specific Properties\n"
			"ro.build.PDA=G900AUCU4CPA1\n"
			"ro.build.hidden_ver=G900AUCU4CPA1\n"
			"ro.config.rm_preload_enabled=0\n"
			"ro.build.changelist=5869384\n"
			"ro.product_ship=true\n"
			"ro.chipname=MSM8974PRO\n"
			"persist.sys.storage_preload=1\n"
			"# end build properties\n"
			"\n"
			"#\n"
			"# HWUI_BUILD_PROPERTIES\n"
			"#\n"
			"ro.hwui.texture_cache_size=50\n"
			"ro.hwui.layer_cache_size=34\n"
			"ro.hwui.path_cache_size=10\n"
			"ro.hwui.shape_cache_size=4\n"
			"ro.hwui.gradient_cache_size=2\n"
			"ro.hwui.drop_shadow_cache_size=6\n"
			"ro.hwui.r_buffer_cache_size=4\n"
			"ro.hwui.text_small_cache_width=2048\n"
			"ro.hwui.text_small_cache_height=2048\n"
			"ro.hwui.text_large_cache_width=4096\n"
			"ro.hwui.text_large_cache_height=4096\n"
			"ro.hwui.fbo_cache_size=16\n"
			"#\n"
			"# from device/samsung/klteatt/system.prop\n"
			"#\n"
			"#\n"
			"# system.prop for msm8974\n"
			"#\n"
			"\n"
			"# LCD Density\n"
			"ro.sf.lcd_density=480\n"
			"\n"
			"# Evolution RIL (8xxx)\n"
			"rild.libpath=/system/lib/libsec-ril.so\n"
			"rild.libargs=-d /dev/smd0\n"
			"ril.subscription.types=NV,RUIM\n"
			"DEVICE_PROVISIONED=1\n"
			"\n"
			"debug.sf.hw=1\n"
			"debug.egl.hw=1\n"
			"debug.composition.type=c2d\n"
			"persist.hwc.mdpcomp.enable=true\n"
			"debug.mdpcomp.logs=0\n"
			"dalvik.vm.heapsize=36m\n"
			"dev.pm.dyn_samplingrate=1\n"
			"persist.demo.hdmirotationlock=false\n"
			"\n"
			"ro.hdmi.enable=true\n"
			"persist.speaker.prot.enable=false\n"
			"qcom.hw.aac.encoder=true\n"
			"#\n"
			"# system props for the cne module\n"
			"#\n"
			"#persist.cne.feature=1\n"
			"\n"
			"#system props for the MM modules\n"
			"media.stagefright.enable-player=true\n"
			"media.stagefright.enable-http=true\n"
			"media.stagefright.enable-aac=true\n"
			"media.stagefright.enable-qcp=true\n"
			"media.stagefright.enable-fma2dp=true\n"
			"media.stagefright.enable-scan=true\n"
			"mmp.enable.3g2=true\n"
			"mm.enable.smoothstreaming=true\n"
			"media.aac_51_output_enabled=true\n"
			"#37491 is decimal sum of supported codecs in AAL\n"
			"#codecs: AVI AC3 ASF AAC QCP DTS 3G2 MP2TS\n"
			"mm.enable.qcom_parser=37491\n"
			"\n"
			"# VIDC: debug_levels\n"
			"# 1:ERROR 2:HIGH 4:LOW 0:NOLOGS 7:AllLOGS\n"
			"vidc.debug.level=1\n"
			"#\n"
			"ro.data.large_tcp_window_size=true\n"
			"\n"
			"# system prop for opengles version\n"
			"#\n"
			"# 196608 is decimal for 0x30000 to report version 3\n"
			"ro.opengles.version=196608\n"
			"\n"
			"# System property for cabl\n"
			"ro.qualcomm.cabl=1\n"
			"\n"
			"#\n"
			"# System props for bluetooth\n"
			"# System prop to turn on hfp client\n"
			"bluetooth.hfp.client=1\n"
			"\n"
			"#\n"
			"# System props for bluetooth LE Always on feature\n"
			"#\n"
			"ro.bluetooth.alwaysbleon=true\n"
			"\n"
			"#Simulate sdcard on /data/media\n"
			"#\n"
			"persist.fuse_sdcard=true\n"
			"\n"
			"#\n"
			"#snapdragon value add features\n"
			"#\n"
			"ro.qc.sdk.audio.ssr=false\n"
			"##fluencetype can be \"fluence\" or \"fluencepro\" or \"none\"\n"
			"ro.qc.sdk.audio.fluencetype=none\n"
			"persist.audio.fluence.voicecall=true\n"
			"persist.audio.fluence.voicerec=false\n"
			"persist.audio.fluence.speaker=true\n"
			"\n"
			"ro.qc.sdk.sensors.gestures=true\n"
			"ro.qc.sdk.gestures.camera=false\n"
			"ro.qc.sdk.camera.facialproc=false\n"
			"# system prop for NFC DT\n"
			"ro.nfc.port=I2C\n"
			"#property to enable user to access Google WFD settings.\n"
			"persist.debug.wfd.enable=1\n"
			"#property to choose between virtual/external wfd display\n"
			"persist.sys.wfd.virtual=0\n"
			"tunnel.audio.encode = true\n"
			"\n"
			"#use VERY_HIGH_QUALITY for audio resampler\n"
			"af.resampler.quality=4\n"
			"\n"
			"#Buffer size in kbytes for compress offload playback\n"
			"audio.offload.buffer.size.kb=32\n"
			"\n"
			"#Enable offload audio video playback by default\n"
			"av.offload.enable=true\n"
			"\n"
			"#enable voice path for PCM VoIP by default\n"
			"use.voice.path.for.pcm.voip=true\n"
			"\n"
			"#hwui properties\n"
			"ro.hwui.texture_cache_size=72\n"
			"ro.hwui.layer_cache_size=48\n"
			"ro.hwui.r_buffer_cache_size=8\n"
			"ro.hwui.path_cache_size=32\n"
			"ro.hwui.gradient_cache_size=1\n"
			"ro.hwui.drop_shadow_cache_size=6\n"
			"ro.hwui.texture_cache_flushrate=0.4\n"
			"ro.hwui.text_small_cache_width=1024\n"
			"ro.hwui.text_small_cache_height=1024\n"
			"ro.hwui.text_large_cache_width=2048\n"
			"ro.hwui.text_large_cache_height=1024\n"
			"\n"
			"#disable dsp gapless mode by default\n"
			"audio.offload.gapless.enabled=false\n"
			"\n"
			"\n"
			"# Enable time services daemon\n"
			"persist.timed.enable=true\n"
			"\n"
			"# Data modules (For evolution RIL model)\n"
			"ro.use_data_netmgrd=false\n"
			"persist.data.netmgrd.qos.enable=false\n"
			"\n"
			"# SAMP SDHA\n"
			"ro.config.oomminfree_high32=73728,92160,110592,129024,147456,184320\n"
			"\n"
			"#\n"
			"# ADDITIONAL_BUILD_PROPERTIES\n"
			"#\n"
			"ro.astcenc.astcsupport=0\n"
			"ro.mct.compressiontype=ETC2\n"
			"ro.config.tima=1\n"
			"ro.config.timaversion=3.0\n"
			"ro.config.rkp=true\n"
			"ro.use_data_netmgrd=false\n"
			"ro.config.alarm_alert=Morning_flower.ogg\n"
			"ro.config.ringtone=ATT_Firefly_Default.ogg\n"
			"ro.config.notification_sound=Whisper.ogg\n"
			"ro.config.ringtone_2=Basic_Bell.ogg\n"
			"ro.config.notification_sound_2=S_Charming_Bell.ogg\n"
			"keyguard.no_require_sim=true\n"
			"ro.com.android.dateformat=MM-dd-yyyy\n"
			"ro.carrier=unknown\n"
			"ro.com.google.clientidbase=android-samsung\n"
			"ro.security.icd.flagmode=single\n"
			"ro.vendor.extension_library=libqti-perfd-client.so\n"
			"persist.radio.apm_sim_not_pwdn=1\n"
			"dalvik.vm.heapstartsize=8m\n"
			"dalvik.vm.heapgrowthlimit=128m\n"
			"dalvik.vm.heapsize=512m\n"
			"dalvik.vm.heaptargetutilization=0.75\n"
			"dalvik.vm.heapminfree=2m\n"
			"dalvik.vm.heapmaxfree=8m\n"
			"ro.build.scafe=americano\n"
			"ro.build.scafe.size=short\n"
			"ro.build.scafe.shot=single\n"
			"ro.build.scafe.cream=white\n"
			"ro.sec.fle.encryption=true\n"
			"ro.hdcp2.rx=tz\n"
			"media.enable-commonsource=true\n"
			"ro.secwvk=144\n"
			"ro.securestorage.support=true\n"
			"security.mdpp=None\n"
			"ro.security.mdpp.ver=1.1\n"
			"ro.security.mdpp.release=4\n"
			"ro.security.vpnpp.ver=1.4\n"
			"ro.security.vpnpp.release=5.3\n"
			"security.mdpp.result=None\n"
			"ro.security.mdpp.ux=Enabled\n"
			"ro.config.dha_cached_max=8\n"
			"ro.config.dha_empty_init=36\n"
			"ro.config.dha_empty_max=36\n"
			"ro.config.dha_th_rate=1.83\n"
			"ro.config.ldha_ext_enable=true\n"
			"ro.error.receiver.default=com.samsung.receiver.error\n"
			"ro.security.reactive.active=1\n"
			"ro.smps.enable=true\n"
			"ro.setupwizard.mode=DISABLED\n"
			"ro.com.google.clientidbase.ms=android-att-us\n"
			"ro.com.google.clientidbase.am=android-att-us\n"
			"ro.com.google.clientidbase.yt=android-samsung\n"
			"ro.com.google.clientidbase.gmm=android-samsung\n"
			"ro.com.google.gmsversion=5.1_r2\n"
			"persist.sys.dalvik.vm.lib.2=libart.so\n"
			"ro.build.selinux=1\n"
			"dalvik.vm.isa.arm.features=div\n"
			"ro.config.knox=v30\n"
			"ro.kernel.qemu=0\n"
			"net.bt.name=Android\n"
			"dalvik.vm.stack-trace-file=/data/anr/traces.txt\n"
			"persist.gps.qc_nlp_in_use=1\n"
			"persist.loc.nlp_name=com.qualcomm.location\n"
			"ro.gps.agps_provider=1\n"
			"ro.pip.gated=0\n"
			"ro.build.aapt.config.prefer=xxhdpi\n"
			"ro.build.version.sdl=2202\n"
			"\n",
	},
	{
		.path = "/sys/devices/system/cpu/kernel_max",
		.size = 2,
		.content = "3\n",
	},
	{
		.path = "/sys/devices/system/cpu/possible",
		.size = 4,
		.content = "0-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/present",
		.size = 4,
		.content = "0-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq",
		.size = 8,
		.content = "2457600\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq",
		.size = 7,
		.content = "300000\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/physical_package_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/core_siblings_list",
		.size = 4,
		.content = "0-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/core_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/thread_siblings_list",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpufreq/cpuinfo_max_freq",
		.size = 8,
		.content = "2457600\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpufreq/cpuinfo_min_freq",
		.size = 7,
		.content = "300000\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/topology/physical_package_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/topology/core_siblings_list",
		.size = 4,
		.content = "0-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/topology/core_id",
		.size = 2,
		.content = "2\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/topology/thread_siblings_list",
		.size = 2,
		.content = "2\n",
	},
	{ NULL },
};
