struct cpuinfo_mock_file filesystem[] = {
	{
		.path = "/proc/cpuinfo",
		.size = 314,
		.content =
			"Processor\t: ARMv7 Processor rev 5 (v7l)\n"
			"processor\t: 0\n"
			"BogoMIPS\t: 18.31\n"
			"Features\t: swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt \n"
			"CPU implementer\t: 0x41\n"
			"CPU architecture: 7\n"
			"CPU variant\t: 0x0\n"
			"CPU part\t: 0xc07\n"
			"CPU revision\t: 5\n"
			"\n"
			"Hardware\t: MT6595\n"
			"Revision\t: 0000\n"
			"Serial\t\t: 0000000000000000\n",
	},
	{
		.path = "/system/build.prop",
		.size = 5248,
		.content =
			"# begin build properties\n"
			"# autogenerated by buildinfo.sh\n"
			"ro.build.id=KOT49H\n"
			"ro.build.display.id=VIBEUI_V2.0_1514_5.128.1_ST_X2-TO\n"
			"ro.build.version.incremental=VIBEUI_V2.0_1514_5.128.1_ST_X2-TO\n"
			"ro.custom.build.version=VIBEUI_V2.0_1514_5.128.1_ST_X2-TO\n"
			"ro.build.version.sdk=19\n"
			"ro.build.version.codename=REL\n"
			"ro.build.version.release=4.4.2\n"
			"ro.build.date=Thu Apr  2 11:48:59 CST 2015\n"
			"ro.build.date.utc=1427946539\n"
			"ro.build.type=user\n"
			"ro.build.user=buildslave\n"
			"ro.build.host=shws45\n"
			"ro.build.tags=release-keys\n"
			"ro.product.model=Lenovo X2-TO\n"
			"ro.product.brand=Lenovo\n"
			"ro.product.name=x2to\n"
			"ro.product.device=X2-TO\n"
			"ro.product.board=x2to\n"
			"ro.product.cpu.abi=armeabi-v7a\n"
			"ro.product.cpu.abi2=armeabi\n"
			"ro.product.manufacturer=LENOVO\n"
			"ro.product.locale.language=en\n"
			"ro.product.locale.region=US\n"
			"ro.wifi.channels=\n"
			"ro.board.platform=\n"
			"# ro.build.product is obsolete; use ro.product.device\n"
			"ro.build.product=X2-TO\n"
			"# Do not try to parse ro.build.description or .fingerprint\n"
			"ro.build.description=x2to-user 4.4.2 KOT49H VIBEUI_V2.0_1514_5.128.1_ST_X2-TO dev-keys\n"
			"ro.build.fingerprint=Lenovo/x2to/X2-TO:4.4.2/KOT49H/VIBEUI_V2.0_1514_5.128.1_ST_X2-TO.:user/release-keys\n"
			"ro.build.flavor=\n"
			"ro.build.characteristics=default\n"
			"# end build properties\n"
			"\n"
			"# begin mediatek build properties\n"
			"ro.mediatek.version.release=ALPS.KK1.MP11.V1.9\n"
			"ro.mediatek.platform=MT6595\n"
			"ro.mediatek.chip_ver=S01\n"
			"ro.mediatek.version.branch=KK1.MP11\n"
			"ro.mediatek.version.sdk=2\n"
			"# end mediatek build properties\n"
			"#\n"
			"# from out/target/product/x2to/obj/CUSTGEN/config/system.prop\n"
			"#\n"
			"#\n"
			"# system.prop for generic sdk\n"
			"#\n"
			"\n"
			"rild.libpath=/system/lib/mtk-ril.so\n"
			"rild.libargs=-d /dev/ttyC0\n"
			"\n"
			"\n"
			"# MTK, Infinity, 20090720 {\n"
			"wifi.interface=wlan0\n"
			"# MTK, Infinity, 20090720 }\n"
			"\n"
			"# MTK, mtk03034, 20101210 {\n"
			"ro.mediatek.wlan.wsc=1\n"
			"# MTK, mtk03034 20101210}\n"
			"# MTK, mtk03034, 20110318 {\n"
			"ro.mediatek.wlan.p2p=1\n"
			"# MTK, mtk03034 20110318}\n"
			"\n"
			"# MTK, mtk03034, 20101213 {\n"
			"mediatek.wlan.ctia=0\n"
			"# MTK, mtk03034 20101213}\n"
			"\n"
			"\n"
			"#\n"
			"wifi.tethering.interface=ap0\n"
			"#\n"
			"\n"
			"ro.opengles.version=196608\n"
			"\n"
			"wifi.direct.interface=p2p0\n"
			"dalvik.vm.heapgrowthlimit=128m\n"
			"dalvik.vm.heapsize=256m\n"
			"\n"
			"# lenovo-sw, chenzz3, 2014-07-30, override dalvik heap settings, begin\n"
			"dalvik.vm.heapstartsize=8m\n"
			"dalvik.vm.heapgrowthlimit=192m\n"
			"dalvik.vm.heapsize=512m\n"
			"dalvik.vm.heapminfree=8m\n"
			"dalvik.vm.heapmaxfree=32m\n"
			"dalvik.vm.heaptargetutilization=0.75\n"
			"# lenovo-sw, chenzz3, 2014-07-30, override dalvik heap settings, end\n"
			"\n"
			"# USB MTP WHQL\n"
			"ro.sys.usb.mtp.whql.enable=0\n"
			"\n"
			"# Power off opt in IPO\n"
			"sys.ipo.pwrdncap=2\n"
			"\n"
			"# Switching Menu of Mass storage and MTP\n"
			"ro.sys.usb.storage.type=mtp,mass_storage\n"
			"\n"
			"# USB BICR function\n"
			"ro.sys.usb.bicr=yes\n"
			"\n"
			"# USB Charge only function\n"
			"ro.sys.usb.charging.only=yes\n"
			"\n"
			"# audio\n"
			"ro.camera.sound.forced=0\n"
			"ro.audio.silent=0\n"
			"\n"
			"ro.zygote.preload.enable=0\n"
			"\n"
			"# disable IPO shutdown for development\n"
			"#Begin,Lenovo-sw duxu1 add 2014-07-01, enable ipo.\n"
			"sys.ipo.disable=0\n"
			"#sys.ipo.disable=1\n"
			"#End,Lenovo-sw duxu1 add 2014-07-01, enable ipo.\n"
			"\n"
			"#Begin,Lenovo-sw duxu1 add 2015-01-07, disable MTK feature.\n"
			"dalvik.vm.debug=0x600\n"
			"#End,Lenovo-sw duxu1 add 2015-01-07, disable MTK feature.\n"
			"\n"
			"#Begin,Lenovo-sw niejl1 add 2014-05-20, add lenovo features.\n"
			"ro.lenovo.series=VIBE X2\n"
			"#End,Lenovo-sw niejl1 add 2014-05-20, add lenovo features.\n"
			"\n"
			"\n"
			"#\n"
			"# ADDITIONAL_BUILD_PROPERTIES\n"
			"#\n"
			"ro.config.ringtone=Fantastic_Clang.ogg\n"
			"ro.config.ringtone_2=Fantastic_Clang.ogg\n"
			"ro.config.alarm_alert=New_Morning.ogg\n"
			"ro.config.sms_notifi_sound=Bump.ogg\n"
			"ro.config.sms_notifi_sound_2=Bump.ogg\n"
			"ro.config.notification_sound=Notice.ogg\n"
			"ro.com.lenovo.smart.config=7\n"
			"persist.backgrounddata.enable=false\n"
			"ro.lenovo.adb=apkctl,speedup\n"
			"ro.sf.lcd_density=480\n"
			"ro.ctaversion.enable=false\n"
			"ro.lenovo.region=prc\n"
			"ro.lenovo.device=phone\n"
			"ro.lenovo.sim=dsda\n"
			"ro.lenovo.operator=open\n"
			"ro.lenovo.slowmotion=true\n"
			"ro.lenovo.platform=mtk\n"
			"ro.lenovo.bqb=pass\n"
			"ro.lenovo.wificert=no\n"
			"ro.lenovo.cta=false\n"
			"ro.lenovo.videocall=false\n"
			"ro.lenovo.signalbars=five\n"
			"persist.lenovo.ltetype=CSFB\n"
			"persist.sys.timezone=Asia/Shanghai\n"
			"ro.com.google.clientbase=android-lenovo\n"
			"ro.lenovo.core.version=master(PRE_V1.0.8)\n"
			"persist.gemini.sim_num=2\n"
			"ro.gemini.smart_sim_switch=false\n"
			"ro.gemini.smart_3g_switch=0\n"
			"ro.gemini.sim_switch_policy=1\n"
			"ril.specific.sm_cause=0\n"
			"bgw.current3gband=0\n"
			"ril.external.md=2\n"
			"ro.btstack=blueangel\n"
			"ro.sf.hwrotation=0\n"
			"ril.current.share_modem=1\n"
			"curlockscreen=1\n"
			"ro.mediatek.gemini_support=true\n"
			"persist.radio.fd.counter=15\n"
			"persist.radio.fd.off.counter=5\n"
			"persist.radio.fd.r8.counter=15\n"
			"persist.radio.fd.off.r8.counter=5\n"
			"drm.service.enabled=true\n"
			"fmradio.driver.enable=1\n"
			"ril.first.md=1\n"
			"ril.flightmode.poweroffMD=0\n"
			"ril.telephony.mode=0\n"
			"dalvik.vm.mtk-stack-trace-file=/data/anr/mtk_traces.txt\n"
			"persist.mtk.anr.mechanism=1\n"
			"mediatek.wlan.chip=MT6630\n"
			"mediatek.wlan.module.postfix=_mt6630\n"
			"ril.radiooff.poweroffMD=0\n"
			"sys.lenovo.romui.version.sdk=2\n"
			"persist.mtk.wcn.combo.chipid=-1\n"
			"ter.service.enable=0\n"
			"mediatek.extmd.usbport=0\n"
			"persist.sys.display.clearMotion=0\n"
			"persist.clearMotion.fblevel.nrm=255\n"
			"persist.clearMotion.fblevel.bdr=255\n"
			"ro.lte.dc.support=0\n"
			"ril.active.md=0\n"
			"wfd.dummy.enable=1\n"
			"ro.product.sw.internal.version=X2-TO_USR_ST1514_5.128.1_1504021143_MP11V1.9_CN\n"
			"ro.product.hw.version=H201\n"
			"ro.product.particular.version=LENOVO_FUJIAN\n"
			"persist.sys.dalvik.vm.lib=libdvm.so\n"
			"ro.hwui.disable_cache_fbo_size=false\n"
			"net.bt.name=Android\n"
			"dalvik.vm.stack-trace-file=/data/anr/traces.txt\n",
	},
	{
		.path = "/sys/devices/system/cpu/kernel_max",
		.size = 2,
		.content = "7\n",
	},
	{
		.path = "/sys/devices/system/cpu/possible",
		.size = 4,
		.content = "0-7\n",
	},
	{
		.path = "/sys/devices/system/cpu/present",
		.size = 4,
		.content = "0-7\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq",
		.size = 8,
		.content = "1690000\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq",
		.size = 7,
		.content = "403000\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/physical_package_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/core_siblings_list",
		.size = 4,
		.content = "0-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/core_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/thread_siblings_list",
		.size = 2,
		.content = "0\n",
	},
	{ NULL },
};
