struct cpuinfo_mock_file filesystem[] = {
	{
		.path = "/proc/cpuinfo",
		.size = 1141,
		.content =
			"processor\t: 0\n"
			"model name\t: ARMv7 Processor rev 0 (v7l)\n"
			"BogoMIPS\t: 38.40\n"
			"Features\t: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 \n"
			"CPU implementer\t: 0x41\n"
			"CPU architecture: 7\n"
			"CPU variant\t: 0x0\n"
			"CPU part\t: 0xd03\n"
			"CPU revision\t: 0\n"
			"\n"
			"processor\t: 1\n"
			"model name\t: ARMv7 Processor rev 0 (v7l)\n"
			"BogoMIPS\t: 38.40\n"
			"Features\t: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 \n"
			"CPU implementer\t: 0x41\n"
			"CPU architecture: 7\n"
			"CPU variant\t: 0x0\n"
			"CPU part\t: 0xd03\n"
			"CPU revision\t: 0\n"
			"\n"
			"processor\t: 2\n"
			"model name\t: ARMv7 Processor rev 0 (v7l)\n"
			"BogoMIPS\t: 38.40\n"
			"Features\t: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 \n"
			"CPU implementer\t: 0x41\n"
			"CPU architecture: 7\n"
			"CPU variant\t: 0x0\n"
			"CPU part\t: 0xd03\n"
			"CPU revision\t: 0\n"
			"\n"
			"processor\t: 3\n"
			"model name\t: ARMv7 Processor rev 0 (v7l)\n"
			"BogoMIPS\t: 38.40\n"
			"Features\t: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 \n"
			"CPU implementer\t: 0x41\n"
			"CPU architecture: 7\n"
			"CPU variant\t: 0x0\n"
			"CPU part\t: 0xd03\n"
			"CPU revision\t: 0\n"
			"\n"
			"Hardware\t: Qualcomm Technologies, Inc MSM8916\n"
			"Revision\t: 0009\n"
			"Serial\t\t: 0000000000000000\n"
			"Processor\t: ARMv7 Processor rev 0 (v7l)\n",
	},
	{
		.path = "/system/build.prop",
		.size = 9576,
		.content =
			"\n"
			"# begin build properties\n"
			"# autogenerated by buildinfo.sh\n"
			"ro.build.id=LMY47V\n"
			"ro.build.display.id=LMY47V\n"
			"ro.build.version.incremental=1611917394609\n"
			"ro.build.version.sdk=22\n"
			"ro.build.version.codename=REL\n"
			"ro.build.version.all_codenames=REL\n"
			"ro.build.version.release=5.1.1\n"
			"ro.build.version.security_patch=2016-04-01\n"
			"ro.build.version.base_os=\n"
			"ro.build.date=Thu Apr 28 17:42:11 KST 2016\n"
			"ro.build.date.utc=1461832931\n"
			"ro.build.type=user\n"
			"ro.build.user=jenkins\n"
			"ro.build.host=LGEACI6R2\n"
			"ro.build.tags=release-keys\n"
			"ro.build.flavor=m216_global_com-user\n"
			"ro.product.model=LG-K420\n"
			"ro.product.brand=lge\n"
			"ro.product.name=m216_global_com\n"
			"ro.product.device=m216\n"
			"ro.product.board=msm8916\n"
			"# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,\n"
			"# use ro.product.cpu.abilist instead.\n"
			"ro.product.cpu.abi=armeabi-v7a\n"
			"ro.product.cpu.abi2=armeabi\n"
			"ro.product.cpu.abilist=armeabi-v7a,armeabi\n"
			"ro.product.cpu.abilist32=armeabi-v7a,armeabi\n"
			"ro.product.cpu.abilist64=\n"
			"ro.product.manufacturer=LGE\n"
			"ro.product.locale.language=en\n"
			"ro.product.locale.region=GB\n"
			"ro.wifi.channels=11\n"
			"ro.board.platform=msm8916\n"
			"# ro.build.product is obsolete; use ro.product.device\n"
			"ro.build.product=m216\n"
			"# Do not try to parse description, fingerprint, or thumbprint\n"
			"ro.build.description=m216_global_com-user 5.1.1 LMY47V 1611917394609 release-keys\n"
			"ro.build.fingerprint=lge/m216_global_com/m216:5.1.1/LMY47V/1611917394609:user/release-keys\n"
			"ro.build.characteristics=default\n"
			"ro.lge.lguiversion=4.2\n"
			"# end build properties\n"
			"#\n"
			"# from device/lge/epsilon0c/qcom/device/msm8916_32/system.prop\n"
			"#\n"
			"#\n"
			"# system.prop for msm8916\n"
			"#\n"
			"\n"
			"#rild.libpath=/system/lib/libreference-ril.so\n"
			"rild.libpath=/system/vendor/lib/libril-qc-qmi-1.so\n"
			"rild.libargs=-d /dev/smd0\n"
			"persist.rild.nitz_plmn=\n"
			"persist.rild.nitz_long_ons_0=\n"
			"persist.rild.nitz_long_ons_1=\n"
			"persist.rild.nitz_long_ons_2=\n"
			"persist.rild.nitz_long_ons_3=\n"
			"persist.rild.nitz_short_ons_0=\n"
			"persist.rild.nitz_short_ons_1=\n"
			"persist.rild.nitz_short_ons_2=\n"
			"persist.rild.nitz_short_ons_3=\n"
			"#persist.radio.rat_on=combine\n"
			"ril.subscription.types=NV,RUIM\n"
			"DEVICE_PROVISIONED=1\n"
			"# Start in cdma mode\n"
			"#ro.telephony.default_network=5\n"
			"\n"
			"debug.sf.hw=1\n"
			"debug.egl.hw=1\n"
			"persist.hwc.mdpcomp.enable=true\n"
			"debug.mdpcomp.logs=0\n"
			"dalvik.vm.heapsize=36m\n"
			"dev.pm.dyn_samplingrate=1\n"
			"persist.demo.hdmirotationlock=false\n"
			"debug.enable.sglscale=1\n"
			"\n"
			"#ro.hdmi.enable=true\n"
			"#tunnel.decode=true\n"
			"#tunnel.audiovideo.decode=true\n"
			"#lpa.decode=false\n"
			"#lpa.use-stagefright=true\n"
			"#persist.speaker.prot.enable=false\n"
			"\n"
			"#\n"
			"# system props for the cne module\n"
			"#\n"
			"persist.cne.feature=1\n"
			"\n"
			"#system props for the MM modules\n"
			"media.stagefright.enable-player=true\n"
			"media.stagefright.enable-http=true\n"
			"media.stagefright.enable-aac=true\n"
			"media.stagefright.enable-qcp=true\n"
			"media.stagefright.enable-fma2dp=true\n"
			"media.stagefright.enable-scan=true\n"
			"media.msm8939hw=0\n"
			"media.msm8929hw=0\n"
			"media.swhevccodectype=0\n"
			"mm.enable.smoothstreaming=true\n"
			"mmp.enable.3g2=true\n"
			"media.aac_51_output_enabled=true\n"
			"#codecs: DivX DivXHD AVI AC3 ASF AAC QCP DTS 3G2 MP2TS\n"
			"mm.enable.qcom_parser=3183219\n"
			"\n"
			"#Trim properties\n"
			"ro.sys.fw.use_trim_settings=true\n"
			"ro.sys.fw.empty_app_percent=50\n"
			"ro.sys.fw.trim_empty_percent=100\n"
			"ro.sys.fw.trim_cache_percent=100\n"
			"ro.sys.fw.trim_enable_memory=1073741824\n"
			"\n"
			"# Default to AwesomePlayer\n"
			"#media.stagefright.use-awesome=true\n"
			"\n"
			"#\n"
			"# system props for the data modules\n"
			"#\n"
			"ro.use_data_netmgrd=true\n"
			"persist.data.netmgrd.qos.enable=true\n"
			"\n"
			"#system props for time-services\n"
			"persist.timed.enable=true\n"
			"\n"
			"#\n"
			"# system prop for opengles version\n"
			"#\n"
			"# 196608 is decimal for 0x30000 to report version 3\n"
			"ro.opengles.version=196608\n"
			"\n"
			"# System property for cabl\n"
			"ro.qualcomm.cabl=0\n"
			"\n"
			"#\n"
			"# System props for telephony\n"
			"# System prop to turn on CdmaLTEPhone always\n"
			"#telephony.lteOnCdmaDevice=1\n"
			"#\n"
			"# System props for bluetooh\n"
			"# System prop to turn on hfp client\n"
			"bluetooth.hfp.client=1\n"
			"\n"
			"#Simulate sdcard on /data/media\n"
			"#\n"
			"persist.fuse_sdcard=true\n"
			"\n"
			"#\n"
			"#snapdragon value add features\n"
			"#\n"
			"ro.qc.sdk.audio.ssr=false\n"
			"##fluencetype can be \"fluence\" or \"fluencepro\" or \"none\"\n"
			"ro.qc.sdk.audio.fluencetype=none\n"
			"persist.audio.fluence.voicecall=true\n"
			"persist.audio.fluence.voicerec=false\n"
			"persist.audio.fluence.speaker=true\n"
			"#Set for msm8916\n"
			"tunnel.audio.encode = false\n"
			"#Buffer size in kbytes for compress offload playback\n"
			"audio.offload.buffer.size.kb=32\n"
			"#Minimum duration for offload playback in secs\n"
			"audio.offload.min.duration.secs=30\n"
			"#Enable offload audio video playback by default\n"
			"av.offload.enable=false\n"
			"#enable voice path for PCM VoIP by default\n"
			"use.voice.path.for.pcm.voip=true\n"
			"#\n"
			"#System property for FM transmitter\n"
			"#\n"
			"#ro.fm.transmitter=false\n"
			"#enable dsp gapless mode by default\n"
			"audio.offload.gapless.enabled=true\n"
			"\n"
			"#// LGE_CHANGE_S, [Net_Patch_0300][CALL_FRW][COMMON], 2012-05-25, Airplane Mode Pop-Up display property value {\n"
			"ro.airplane.phoneapp=1\n"
			"#// LGE_CHANGE_E, [Net_Patch_0300][CALL_FRW][COMMON], 2012-05-25, Airplane Mode Pop-Up display property value }\n"
			"\n"
			"#Audio voice concurrency related flags\n"
			"voice.playback.conc.disabled=true\n"
			"voice.record.conc.disabled=true\n"
			"voice.voip.conc.disabled=true\n"
			"\n"
			"#Set composition for USB\n"
			"#persist.sys.usb.config=diag,serial_smd,rmnet_bam,adb\n"
			"\n"
			"#Set read only default composition for USB\n"
			"#ro.sys.usb.default.config=diag,serial_smd,rmnet_bam,adb\n"
			"\n"
			"#property to enable user to access Google WFD settings\n"
			"persist.debug.wfd.enable=1\n"
			"#propery to enable VDS WFD solution\n"
			"persist.hwc.enable_vds=1\n"
			"\n"
			"#selects CoreSight configuration to enable\n"
			"persist.debug.coresight.config=stm-events\n"
			"\n"
			"#property to enable DS2 dap\n"
			"audio.dolby.ds2.enabled=false\n"
			"\n"
			"#\n"
			"# ADDITIONAL_BUILD_PROPERTIES\n"
			"#\n"
			"log.tag.GpsLocationProvider=DEBUG\n"
			"log.tag.LocationManagerService=DEBUG\n"
			"log.tag.NlpProxy=DEBUG\n"
			"log.tag.LocSvc_java=DEBUG\n"
			"log.tag.LgeGpsIndicator=DEBUG\n"
			"ro.com.lge.mada=gms_3.1\n"
			"persist.sys.strictmode.disable=true\n"
			"persist.sys.cust.lte_config=true\n"
			"ro.lge.lcd_default_brightness=166\n"
			"ro.lge.sensor_chip=qct_kernel\n"
			"persist.lg.data.llkklk=true\n"
			"ro.frp.pst=/dev/block/bootdevice/by-name/persistent\n"
			"net.tethering.noprovisioning=true\n"
			"persist.lg.data.llkklk.exact=true\n"
			"persist.lg.data.fd=-1\n"
			"persist.qcril.disable_retry=true\n"
			"persist.data.netmgrd.qos.enable=false\n"
			"persist.lg.data.vdbg=false\n"
			"persist.lge.appman.firstboot=1\n"
			"persist.service.postboot.enable=0\n"
			"ro.lge.revshare=2015\n"
			"voice.playback.conc.disabled=false\n"
			"voice.record.conc.disabled=false\n"
			"voice.voip.conc.disabled=false\n"
			"persist.sys.media.use-awesome=false\n"
			"wifi.lge.fcc=true\n"
			"sys.knockon.knockoff.distance=10\n"
			"ro.lge.lcd_auto_brightness_mode=false\n"
			"ro.lge.audio_soundexception=true\n"
			"sys.lge.bnrd=0\n"
			"ro.lge.capp_ZDi_O=true\n"
			"lge.zdi.actionsend=false\n"
			"lge.zdi.onactivityresult=true\n"
			"lge.zdi.dragdropintent=false\n"
			"persist.service.main.enable=0\n"
			"persist.service.system.enable=0\n"
			"persist.service.radio.enable=0\n"
			"persist.service.events.enable=0\n"
			"persist.service.kernel.enable=0\n"
			"persist.service.power.enable=0\n"
			"persist.service.memory.enable=0\n"
			"persist.service.packet.enable=0\n"
			"persist.service.crash.enable=0\n"
			"persist.service.storage.low=0\n"
			"persist.service.ccaudit.enable=0\n"
			"persist.service.packet.max=0\n"
			"ro.vendor.extension_library=libqti-perfd-client.so\n"
			"persist.radio.apm_sim_not_pwdn=1\n"
			"ro.carrier=unknown\n"
			"dalvik.vm.heapstartsize=8m\n"
			"dalvik.vm.heapgrowthlimit=96m\n"
			"dalvik.vm.heapsize=256m\n"
			"dalvik.vm.heaptargetutilization=0.75\n"
			"dalvik.vm.heapminfree=2m\n"
			"dalvik.vm.heapmaxfree=8m\n"
			"lge.signed_image=true\n"
			"wlan.chip.vendor=qcom\n"
			"wlan.chip.version=wcn\n"
			"wifi.lge.patch=true\n"
			"wifi.lge.sleeppolicy=0\n"
			"wifi.lge.offdelay=false\n"
			"wlan.lge.concurrency=MCC\n"
			"wlan.lge.supportsimaka=YES\n"
			"wifi.lge.ftm_test=2\n"
			"wifi.lge.common_hotspot=true\n"
			"wlan.lge.dcf.enable=true\n"
			"wlan.lge.passpoint_setting=true\n"
			"wlan.lge.softapwps=true\n"
			"ro.setupwizard.mode=DISABLED\n"
			"ro.lge.sensors_multihal=false\n"
			"persist.service.bt.support.sap=true\n"
			"service.bt.support.busytone=true\n"
			"persist.service.avrcp.browsing=1\n"
			"ro.config.ringtone=01_Life_Is_Good.ogg\n"
			"ro.config.notification_sound=Crystal.ogg\n"
			"ro.config.alarm_alert=Melody_Alarm.ogg\n"
			"ro.config.timer_alert=Timer.ogg\n"
			"persist.audio.nxp=OFF\n"
			"persist.audio.nsenabled=OFF\n"
			"persist.audio.spkcall_2mic=OFF\n"
			"persist.audio.headset_fluence=false\n"
			"persist.audio.sm_fluence=OFF\n"
			"persist.audio.spk_sm_fluence=OFF\n"
			"persist.audio.voip_nsenabled=OFF\n"
			"ro.config.vc_call_vol_steps=6\n"
			"ro.config.vc_call_vol_default=3\n"
			"persist.audio.voice.clarity=none\n"
			"persist.audio.handset_rx_type=DEFAULT\n"
			"persist.audio.fluence.voicecall=none\n"
			"persist.audio.fluence.voicerec=none\n"
			"persist.audio.fluence.speaker=none\n"
			"lge.fm_gain_control_headset=0.53\n"
			"lge.fm_gain_control_speaker=0.70\n"
			"ro.lge.vib_magnitude_index=0,20,40,60,80,100,120,127\n"
			"lge.normalizer.param=version2.0/true/10.0/true/19000/0.5/2500/0.62\n"
			"ro.sdcrypto.syscall=398\n"
			"ro.com.google.gmsversion=5.1_r3\n"
			"ro.com.google.apphider=on\n"
			"ro.lge.capp_cupss.rootdir=/cust\n"
			"persist.data.sbp.update=0\n"
			"drm.service.enabled=true\n"
			"use.voice.path.for.pcm.voip=false\n"
			"ro.build.target_operator=GLOBAL\n"
			"ro.build.target_country=COM\n"
			"ro.lge.swversion=K42010n\n"
			"ro.lge.swversion_short=V10n\n"
			"ro.lge.swversion_rev=0\n"
			"ro.lge.factoryversion=LGK420AT-00-V10n-GLOBAL-COM-APR-28-2016+0\n"
			"ro.telephony.default_network=9\n"
			"ro.lge.custLanguageSet=true\n"
			"ro.build.sbp=1\n"
			"ro.device.hapticfeedback=0\n"
			"ro.lge.singleca.enable=1\n"
			"persist.gsm.sms.disablelog=64\n"
			"ro.sys.fw.bg_apps_limit=24\n"
			"ro.sys.fw.bg_cached_ratio=0.5\n"
			"ro.sys.fw.mOomAdj1=0\n"
			"ro.sys.fw.mOomAdj2=1\n"
			"ro.sys.fw.mOomAdj3=2\n"
			"ro.sys.fw.mOomAdj4=3\n"
			"ro.sys.fw.mOomAdj5=9\n"
			"ro.sys.fw.mOomAdj6=15\n"
			"ro.sys.fw.mOomMinFree1=73728\n"
			"ro.sys.fw.mOomMinFree2=92160\n"
			"ro.sys.fw.mOomMinFree3=110592\n"
			"ro.sys.fw.mOomMinFree4=129024\n"
			"ro.sys.fw.mOomMinFree5=221184\n"
			"ro.sys.fw.mOomMinFree6=322560\n"
			"ro.lge.sar.value=1\n"
			"ro.lge.deny.minfree.change=1\n"
			"persist.sys.dalvik.vm.lib.2=libart.so\n"
			"dalvik.vm.isa.arm.features=div,needfix_835769\n"
			"net.bt.name=Android\n"
			"dalvik.vm.stack-trace-file=/data/anr/traces.txt\n"
			"persist.gps.qc_nlp_in_use=0\n"
			"ro.gps.agps_provider=1\n"
			"ro.pip.gated=0\n"
			"\n",
	},
	{
		.path = "/sys/devices/system/cpu/kernel_max",
		.size = 2,
		.content = "3\n",
	},
	{
		.path = "/sys/devices/system/cpu/possible",
		.size = 4,
		.content = "0-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/present",
		.size = 4,
		.content = "0-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq",
		.size = 8,
		.content = "1209600\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq",
		.size = 7,
		.content = "200000\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/physical_package_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/core_siblings_list",
		.size = 4,
		.content = "0-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/core_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/thread_siblings_list",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/cpufreq/cpuinfo_max_freq",
		.size = 8,
		.content = "1209600\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/cpufreq/cpuinfo_min_freq",
		.size = 7,
		.content = "200000\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/topology/physical_package_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/topology/core_siblings_list",
		.size = 4,
		.content = "0-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/topology/core_id",
		.size = 2,
		.content = "1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/topology/thread_siblings_list",
		.size = 2,
		.content = "1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpufreq/cpuinfo_max_freq",
		.size = 8,
		.content = "1209600\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpufreq/cpuinfo_min_freq",
		.size = 7,
		.content = "200000\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/topology/physical_package_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/topology/core_siblings_list",
		.size = 4,
		.content = "0-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/topology/core_id",
		.size = 2,
		.content = "2\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/topology/thread_siblings_list",
		.size = 2,
		.content = "2\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/cpufreq/cpuinfo_max_freq",
		.size = 8,
		.content = "1209600\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/cpufreq/cpuinfo_min_freq",
		.size = 7,
		.content = "200000\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/topology/physical_package_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/topology/core_siblings_list",
		.size = 4,
		.content = "0-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/topology/core_id",
		.size = 2,
		.content = "3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/topology/thread_siblings_list",
		.size = 2,
		.content = "3\n",
	},
	{ NULL },
};
