struct cpuinfo_mock_file filesystem[] = {
	{
		.path = "/proc/cpuinfo",
		.size = 1025,
		.content =
			"Processor\t: AArch64 Processor rev 1 (aarch64)\n"
			"processor\t: 0\n"
			"min_vddcx\t: 400000\n"
			"min_vddmx\t: 490000\n"
			"BogoMIPS\t: 38.00\n"
			"Features\t: fp asimd evtstrm aes pmull sha1 sha2 crc32\n"
			"CPU implementer\t: 0x51\n"
			"CPU architecture: 8\n"
			"CPU variant\t: 0x2\n"
			"CPU part\t: 0x201\n"
			"CPU revision\t: 1\n"
			"\n"
			"processor\t: 1\n"
			"min_vddcx\t: 400000\n"
			"min_vddmx\t: 490000\n"
			"BogoMIPS\t: 38.00\n"
			"Features\t: fp asimd evtstrm aes pmull sha1 sha2 crc32\n"
			"CPU implementer\t: 0x51\n"
			"CPU architecture: 8\n"
			"CPU variant\t: 0x2\n"
			"CPU part\t: 0x201\n"
			"CPU revision\t: 1\n"
			"\n"
			"processor\t: 2\n"
			"min_vddcx\t: 400000\n"
			"min_vddmx\t: 490000\n"
			"BogoMIPS\t: 38.00\n"
			"Features\t: fp asimd evtstrm aes pmull sha1 sha2 crc32\n"
			"CPU implementer\t: 0x51\n"
			"CPU architecture: 8\n"
			"CPU variant\t: 0x2\n"
			"CPU part\t: 0x205\n"
			"CPU revision\t: 1\n"
			"\n"
			"processor\t: 3\n"
			"min_vddcx\t: 400000\n"
			"min_vddmx\t: 490000\n"
			"BogoMIPS\t: 38.00\n"
			"Features\t: fp asimd evtstrm aes pmull sha1 sha2 crc32\n"
			"CPU implementer\t: 0x51\n"
			"CPU architecture: 8\n"
			"CPU variant\t: 0x2\n"
			"CPU part\t: 0x205\n"
			"CPU revision\t: 1\n"
			"\n"
			"CPU param\t: 267 434 434 633 958 308 436 436 636 1078 \n"
			"Hardware\t: Qualcomm Technologies, Inc MSM8996pro\n",
	},
	{
		.path = "/system/build.prop",
		.size = 5155,
		.content =
			"\n"
			"# begin build properties\n"
			"# autogenerated by buildinfo.sh\n"
			"ro.build.id=NOF26V\n"
			"ro.build.display.id=NOF26V\n"
			"ro.build.version.incremental=3636322\n"
			"ro.build.version.sdk=25\n"
			"ro.build.version.preview_sdk=0\n"
			"ro.build.version.codename=REL\n"
			"ro.build.version.all_codenames=REL\n"
			"ro.build.version.release=7.1.1\n"
			"ro.build.version.security_patch=2017-02-05\n"
			"ro.build.version.base_os=\n"
			"ro.build.date=Fri Jan 13 03:24:11 UTC 2017\n"
			"ro.build.date.utc=1484277851\n"
			"ro.build.type=user\n"
			"ro.build.user=android-build\n"
			"ro.build.host=wpix7.hot.corp.google.com\n"
			"ro.build.tags=release-keys\n"
			"ro.build.flavor=marlin-user\n"
			"ro.build.system_root_image=true\n"
			"ro.build.ab_update=true\n"
			"ro.product.model=Pixel XL\n"
			"ro.product.brand=google\n"
			"ro.product.name=marlin\n"
			"ro.product.device=marlin\n"
			"ro.product.board=marlin\n"
			"# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,\n"
			"# use ro.product.cpu.abilist instead.\n"
			"ro.product.cpu.abi=arm64-v8a\n"
			"ro.product.cpu.abilist=arm64-v8a,armeabi-v7a,armeabi\n"
			"ro.product.cpu.abilist32=armeabi-v7a,armeabi\n"
			"ro.product.cpu.abilist64=arm64-v8a\n"
			"ro.product.manufacturer=Google\n"
			"ro.product.locale=en-US\n"
			"ro.wifi.channels=\n"
			"ro.board.platform=msm8996\n"
			"# ro.build.product is obsolete; use ro.product.device\n"
			"ro.build.product=marlin\n"
			"# Do not try to parse description, fingerprint, or thumbprint\n"
			"ro.build.description=marlin-user 7.1.1 NOF26V 3636322 release-keys\n"
			"ro.build.fingerprint=google/marlin/marlin:7.1.1/NOF26V/3636322:user/release-keys\n"
			"ro.build.characteristics=nosdcard\n"
			"# end build properties\n"
			"\n"
			"#\n"
			"# ADDITIONAL_BUILD_PROPERTIES\n"
			"#\n"
			"ro.product.first_api_level=24\n"
			"dalvik.vm.heapgrowthlimit=256m\n"
			"ro.telephony.default_cdma_sub=0\n"
			"dalvik.vm.heapstartsize=8m\n"
			"dalvik.vm.heapsize=512m\n"
			"dalvik.vm.heaptargetutilization=0.75\n"
			"dalvik.vm.heapminfree=512k\n"
			"dalvik.vm.heapmaxfree=8m\n"
			"ro.vendor.extension_library=libqti-perfd-client.so\n"
			"persist.radio.apm_sim_not_pwdn=1\n"
			"persist.radio.sib16_support=1\n"
			"persist.radio.custom_ecc=1\n"
			"ro.opengles.version=196610\n"
			"ro.hwui.gradient_cache_size=1\n"
			"ro.hwui.drop_shadow_cache_size=6\n"
			"ro.hwui.r_buffer_cache_size=8\n"
			"ro.hwui.texture_cache_flushrate=0.4\n"
			"ro.hwui.text_small_cache_width=1024\n"
			"ro.hwui.text_small_cache_height=1024\n"
			"ro.hwui.text_large_cache_width=2048\n"
			"ro.hwui.text_large_cache_height=1024\n"
			"ro.qc.sdk.audio.fluencetype=fluencepro\n"
			"persist.audio.fluence.voicecall=true\n"
			"persist.audio.fluence.speaker=true\n"
			"persist.audio.fluence.voicecomm=true\n"
			"persist.audio.fluence.voicerec=false\n"
			"af.fast_track_multiplier=1\n"
			"audio_hal.period_size=192\n"
			"persist.camera.gyro.android=4\n"
			"persist.camera.tof.direct=1\n"
			"persist.camera.tnr.preview=1\n"
			"persist.camera.tnr.video=1\n"
			"qcom.bluetooth.soc=rome\n"
			"persist.cne.feature=1\n"
			"persist.radio.data_ltd_sys_ind=1\n"
			"persist.radio.is_wps_enabled=true\n"
			"persist.radio.RATE_ADAPT_ENABLE=1\n"
			"persist.radio.ROTATION_ENABLE=1\n"
			"persist.radio.sw_mbn_update=1\n"
			"persist.radio.videopause.mode=1\n"
			"persist.radio.VT_ENABLE=1\n"
			"persist.radio.VT_HYBRID_ENABLE=1\n"
			"persist.radio.data_con_rprt=true\n"
			"persist.rcs.supported=1\n"
			"rild.libpath=/vendor/lib64/libril-qc-qmi-1.so\n"
			"persist.data.mode=concurrent\n"
			"persist.radio.snapshot_enabled=1\n"
			"persist.radio.snapshot_timer=3\n"
			"persist.data.iwlan.enable=true\n"
			"ro.telephony.default_network=10\n"
			"telephony.lteOnCdmaDevice=1\n"
			"persist.camera.eis.enable=1\n"
			"persist.camera.is_type=4\n"
			"persist.sys.ssr.restart_level=venus,AR6320,slpi,modem,adsp\n"
			"ro.bt.bdaddr_path=/sys/module/bdaddress/parameters/bdaddress\n"
			"ro.cp_system_other_odex=1\n"
			"ro.camera.notify_nfc=1\n"
			"ro.frp.pst=/dev/block/platform/soc/624000.ufshc/by-name/frp\n"
			"sdm.debug.disable_rotator_split=1\n"
			"qdcm.only_pcc_for_trans=1\n"
			"qdcm.diagonal_matrix_mode=1\n"
			"vidc.debug.perf.mode=2\n"
			"ro.crypto.scrypt_params=13:3:1\n"
			"debug.sf.disable_hwc_vds=1\n"
			"audio.adm.buffering.ms=3\n"
			"ro.sf.lcd_density=560\n"
			"ro.config.vc_call_vol_steps=7\n"
			"ro.hwui.texture_cache_size=72\n"
			"ro.hwui.layer_cache_size=48\n"
			"ro.hwui.path_cache_size=32\n"
			"ro.hardware.fingerprint=fpc\n"
			"ro.config.ringtone=Zen.ogg\n"
			"ro.config.notification_sound=Chime.ogg\n"
			"ro.config.alarm_alert=Flow.ogg\n"
			"ro.com.android.dataroaming=false\n"
			"ro.url.legal=http://www.google.com/intl/%s/mobile/android/basic/phone-legal.html\n"
			"ro.url.legal.android_privacy=http://www.google.com/intl/%s/mobile/android/basic/privacy.html\n"
			"ro.com.google.clientidbase=android-google\n"
			"ro.carrier=unknown\n"
			"ro.com.android.wifi-watchlist=GoogleGuest\n"
			"ro.error.receiver.system.apps=com.google.android.gms\n"
			"ro.setupwizard.enterprise_mode=1\n"
			"ro.atrace.core.services=com.google.android.gms,com.google.android.gms.ui,com.google.android.gms.persistent\n"
			"ro.retaildemo.video_path=/data/preloads/demo/retail_demo.mp4\n"
			"ro.com.android.prov_mobiledata=false\n"
			"keyguard.no_require_sim=true\n"
			"drm.service.enabled=true\n"
			"media.mediadrmservice.enable=true\n"
			"ro.setupwizard.rotation_locked=true\n"
			"ro.opa.eligible_device=true\n"
			"ro.facelock.black_timeout=700\n"
			"ro.facelock.det_timeout=2500\n"
			"ro.facelock.rec_timeout=3500\n"
			"ro.facelock.est_max_time=600\n"
			"ro.wallpapers_loc_request_suw=true\n"
			"ro.com.google.ime.theme_id=5\n"
			"ro.storage_manager.enabled=true\n"
			"persist.sys.dalvik.vm.lib.2=libart.so\n"
			"dalvik.vm.isa.arm64.variant=generic\n"
			"dalvik.vm.isa.arm64.features=default\n"
			"dalvik.vm.isa.arm.variant=krait\n"
			"dalvik.vm.isa.arm.features=default\n"
			"net.bt.name=Android\n"
			"dalvik.vm.stack-trace-file=/data/anr/traces.txt\n"
			"ro.build.expect.bootloader=8996-012001-1611091517\n"
			"ro.build.expect.baseband=8996-012511-1611190200\n"
			"\n",
	},
	{
		.path = "/sys/devices/system/cpu/kernel_max",
		.size = 2,
		.content = "3\n",
	},
	{
		.path = "/sys/devices/system/cpu/possible",
		.size = 4,
		.content = "0-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/present",
		.size = 4,
		.content = "0-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq",
		.size = 8,
		.content = "1593600\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq",
		.size = 7,
		.content = "307200\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/physical_package_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/core_siblings_list",
		.size = 4,
		.content = "0-1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/core_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/thread_siblings_list",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/cpufreq/cpuinfo_max_freq",
		.size = 8,
		.content = "1593600\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/cpufreq/cpuinfo_min_freq",
		.size = 7,
		.content = "307200\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/topology/physical_package_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/topology/core_siblings_list",
		.size = 4,
		.content = "0-1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/topology/core_id",
		.size = 2,
		.content = "1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/topology/thread_siblings_list",
		.size = 2,
		.content = "1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpufreq/cpuinfo_max_freq",
		.size = 8,
		.content = "2150400\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpufreq/cpuinfo_min_freq",
		.size = 7,
		.content = "307200\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/topology/physical_package_id",
		.size = 2,
		.content = "1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/topology/core_siblings_list",
		.size = 4,
		.content = "2-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/topology/core_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/topology/thread_siblings_list",
		.size = 2,
		.content = "2\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/cpufreq/cpuinfo_max_freq",
		.size = 8,
		.content = "2150400\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/cpufreq/cpuinfo_min_freq",
		.size = 7,
		.content = "307200\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/topology/physical_package_id",
		.size = 2,
		.content = "1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/topology/core_siblings_list",
		.size = 4,
		.content = "2-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/topology/core_id",
		.size = 2,
		.content = "1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/topology/thread_siblings_list",
		.size = 2,
		.content = "3\n",
	},
	{ NULL },
};
