struct cpuinfo_mock_file filesystem[] = {
	{
		.path = "/proc/cpuinfo",
		.size = 361,
		.content =
			"processor\t: 0\n"
			"model name\t: ARMv7 Processor rev 5 (v7l)\n"
			"Processor\t: ARMv7 Processor rev 5 (v7l)\n"
			"BogoMIPS\t: 1244.61\n"
			"Features\t: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt \n"
			"CPU implementer\t: 0x41\n"
			"CPU architecture: 7\n"
			"CPU variant\t: 0x0\n"
			"CPU part\t: 0xc07\n"
			"CPU revision\t: 5\n"
			"\n"
			"Hardware\t: Leadcore Innopower\n"
			"Revision\t: 0000\n"
			"Serial\t\t: 0000000000000000\n",
	},
	{
		.path = "/system/build.prop",
		.size = 4346,
		.content =
			"# begin build properties\n"
			"# autogenerated by buildinfo.sh\n"
			"ro.build.id=KTU84Q\n"
			"ro.build.version.incremental=V8.0.1.0.KHLCNDG\n"
			"ro.build.version.sdk=19\n"
			"ro.build.version.codename=REL\n"
			"ro.build.version.release=4.4.4\n"
			"ro.build.version.security_patch=2016-08-01\n"
			"ro.build.version.base_os=\n"
			"ro.build.date=Sat Aug 13 16:53:18 CST 2016\n"
			"ro.build.date.utc=1471078398\n"
			"ro.build.type=user\n"
			"ro.build.user=builder\n"
			"ro.build.host=c3-miui-ota-bd21.bj\n"
			"ro.build.tags=release-keys\n"
			"ro.product.brand=Xiaomi\n"
			"ro.product.mod_device=lte26007\n"
			"ro.product.hardware.version=Ver0606\n"
			"ro.product.cpu.abi=armeabi-v7a\n"
			"ro.product.cpu.abi2=armeabi\n"
			"ro.product.locale.language=zh\n"
			"ro.product.locale.region=CN\n"
			"ro.wifi.channels=\n"
			"ro.board.platform=lc1860\n"
			"# ro.build.product is obsolete; use ro.product.device\n"
			"# Do not try to parse ro.build.description or .fingerprint\n"
			"ro.build.description=full_lte26007-user 4.4.4 KTU84Q V8.0.1.0.KHLCNDG release-keys\n"
			"ro.build.fingerprint=Xiaomi/full_lte26007/lte26007:4.4.4/KTU84Q/V8.0.1.0.KHLCNDG:user/release-keys\n"
			"ro.build.characteristics=default\n"
			"# end build properties\n"
			"\n"
			"#\n"
			"# ADDITIONAL_BUILD_PROPERTIES\n"
			"#\n"
			"ro.miui.version.code_time=1469635200\n"
			"ro.miui.ui.version.code=6\n"
			"ro.miui.ui.version.name=V8\n"
			"persist.power.useautobrightadj=true\n"
			"persist.sys.mcd_config_file=/system/etc/mcd_default.conf\n"
			"ro.com.android.dateformat=MM-dd-yyyy\n"
			"ro.carrier=unknown\n"
			"ro.build.mass.production=true\n"
			"persist.sys.install.lc.log=/data/local/log,I1,0,0,I2,0,0,I3,0,0,I4,0,0,I5,0,0,I6,0,0\n"
			"persist.sys.install.max.lc.log=/data/local/log,I1,10,8192,I2,10,8192,I3,10,51200,I4,100,8192,I5,10,8192,I6,10,8192\n"
			"persist.sys.lc.msms=221\n"
			"persist.sys.lc.standby.rat=7,3\n"
			"persist.sys.lc.dual2single=1\n"
			"persist.sys.lc.dynamic.rat=1\n"
			"persist.sys.lc.master.card=10\n"
			"persist.sys.lc.def.cs=0\n"
			"persist.sys.lc.def.ps=0\n"
			"persist.sys.lc.def.sms=0\n"
			"persist.sys.lc.network.model=3\n"
			"persist.sys.lc.check.imei=1\n"
			"persist.sys.lc.network.select.mode=1\n"
			"persist.sys.lc.preferred.network.mode=1\n"
			"ro.build.display.lc.id=L1860_1.00.10.R57_20151110\n"
			"ro.build.factory.mode=0\n"
			"ro.build.display.factory.id=FACTORY-02\n"
			"persist.sys.timezone=Asia/Shanghai\n"
			"debug.hwc.fakevsync=0\n"
			"debug.hwc.logvsync=0\n"
			"debug.sf.gpuoverlay=0\n"
			"debug.sf.sa_enable=1\n"
			"debug.sf.sa_log=0\n"
			"debug.hwc.asyncdisp=1\n"
			"debug.power.loghint=0\n"
			"persist.radio.elog.path=1\n"
			"persist.sys.lc.amt.mmi.station=18\n"
			"ro.installed.fm=1\n"
			"ro.fm.devicename=bcm4343_b2\n"
			"wifi.interface=wlan0\n"
			"ro.opengles.version=196608\n"
			"persist.sys.display_prefer=2\n"
			"persist.sys.display_ce=11\n"
			"sys.haptic.long.weak=0,1,20,21\n"
			"sys.haptic.long.normal=0,14,20,32\n"
			"sys.haptic.long.strong=0,24,20,45\n"
			"sys.haptic.down.weak=0,1,20,21\n"
			"sys.haptic.down.normal=0,12,24,32\n"
			"sys.haptic.down.strong=0,24,20,46\n"
			"sys.haptic.up.weak=0,1,25,26\n"
			"sys.haptic.up.normal=0,10,25,35\n"
			"sys.haptic.up.strong=0,20,25,46\n"
			"sys.haptic.tap.weak=0,8,25,28\n"
			"sys.haptic.tap.normal=0,15,30,40\n"
			"sys.haptic.tap.strong=0,24,32,48\n"
			"ro.config.low_ram=false\n"
			"ro.config.max_starting_bg=8\n"
			"ro.audio.flinger_standbytime_ms=1000\n"
			"dalvik.vm.heapstartsize=8m\n"
			"dalvik.vm.heapgrowthlimit=96m\n"
			"dalvik.vm.heapsize=256m\n"
			"dalvik.vm.heaptargetutilization=0.75\n"
			"dalvik.vm.heapminfree=2m\n"
			"dalvik.vm.heapmaxfree=8m\n"
			"persist.sys.dalvik.vm.lib=libdvm.so\n"
			"net.bt.name=Android\n"
			"dalvik.vm.stack-trace-file=/data/anr/traces.txt\n"
			"ro.miui.has_real_blur=1\n"
			"ro.miui.has_handy_mode_sf=1\n"
			"ro.product.mod_device=lte26007\n"
			"ro.config.sms_received_sound=FadeIn.ogg\n"
			"ro.config.sms_delivered_sound=MessageComplete.ogg\n"
			"ro.com.android.mobiledata=false\n"
			"ro.product.manufacturer=Xiaomi\n"
			"ro.config.elder-ringtone=Angel.mp3\n"
			"keyguard.no_require_sim=true\n"
			"ro.com.android.dataroaming=false\n"
			"persist.sys.mitalk.enable=true\n"
			"ro.config.ringtone=Ring_Synth_04.ogg\n"
			"ro.config.notification_sound=pixiedust.ogg\n"
			"ro.config.alarm_alert=Alarm_Classic.ogg\n"
			"ro.product.cuptsm=XIAOMI|ESE|02|01\n"
			"ro.product.name=full_lte26007\n"
			"ro.build.display.id=KTU84P\n"
			"ro.product.device=lte26007\n"
			"ro.product.board=2014502\n"
			"ro.build.customer=XIAOMI\n"
			"ro.build.product=HM2014502\n"
			"ro.product.model=HM 2A\n"
			"ro.product.real_model=2014502\n"
			"ro.build.display.wtid=SW_S26007A2_V001_M10_XM_USER\n"
			"ro.com.google.clientidbase=android-xiaomi\n"
			"ro.sf.lcd_density=320\n"
			"persist.radio.multisim.config=dsds\n"
			"ro.telephony.default_network=101\n"
			"ro.ril.auto.plmn=0\n"
			"ro.telephony.call_ring.multiple=false\n"
			"ro.ril.resend.sms.full=1\n"
			"ro.ril.modem.pb=0\n"
			"persist.sys.lc.dcrm.config=0\n"
			"persist.sys.button_jack_profile=volume\n"
			"persist.sys.button_jack_switch=0\n"
			"persist.sys.miui_feature_config=/system/etc/miui_feature/lite.conf\n"
			"\n",
	},
	{
		.path = "/sys/devices/system/cpu/kernel_max",
		.size = 2,
		.content = "4\n",
	},
	{
		.path = "/sys/devices/system/cpu/possible",
		.size = 4,
		.content = "0-4\n",
	},
	{
		.path = "/sys/devices/system/cpu/present",
		.size = 4,
		.content = "0-4\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq",
		.size = 8,
		.content = "1495000\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq",
		.size = 7,
		.content = "624000\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/physical_package_id",
		.size = 2,
		.content = "1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/core_siblings_list",
		.size = 4,
		.content = "0-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/core_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/thread_siblings_list",
		.size = 2,
		.content = "0\n",
	},
	{ NULL },
};
