struct cpuinfo_mock_file filesystem[] = {
	{
		.path = "/proc/cpuinfo",
		.size = 819,
		.content =
			"Processor\t: AArch64 Processor rev 1 (aarch64)\n"
			"processor\t: 0\n"
			"BogoMIPS\t: 38.40\n"
			"Features\t: fp asimd evtstrm aes pmull sha1 sha2 crc32\n"
			"CPU implementer\t: 0x51\n"
			"CPU architecture: 8\n"
			"CPU variant\t: 0x2\n"
			"CPU part\t: 0x201\n"
			"CPU revision\t: 1\n"
			"\n"
			"processor\t: 1\n"
			"BogoMIPS\t: 38.40\n"
			"Features\t: fp asimd evtstrm aes pmull sha1 sha2 crc32\n"
			"CPU implementer\t: 0x51\n"
			"CPU architecture: 8\n"
			"CPU variant\t: 0x2\n"
			"CPU part\t: 0x201\n"
			"CPU revision\t: 1\n"
			"\n"
			"processor\t: 2\n"
			"BogoMIPS\t: 38.40\n"
			"Features\t: fp asimd evtstrm aes pmull sha1 sha2 crc32\n"
			"CPU implementer\t: 0x51\n"
			"CPU architecture: 8\n"
			"CPU variant\t: 0x2\n"
			"CPU part\t: 0x205\n"
			"CPU revision\t: 1\n"
			"\n"
			"processor\t: 3\n"
			"BogoMIPS\t: 38.40\n"
			"Features\t: fp asimd evtstrm aes pmull sha1 sha2 crc32\n"
			"CPU implementer\t: 0x51\n"
			"CPU architecture: 8\n"
			"CPU variant\t: 0x2\n"
			"CPU part\t: 0x205\n"
			"CPU revision\t: 1\n"
			"\n"
			"Hardware\t: Qualcomm Technologies, Inc MSM8996pro\n",
	},
	{
		.path = "/system/build.prop",
		.size = 12628,
		.content =
			"\n"
			"#\n"
			"#\n"
			"#\n"
			"#\n"
			"# autogenerated by oem_buildinfo.sh\n"
			"ro.frp.pst=/dev/block/bootdevice/by-name/config\n"
			"ro.build.product=OnePlus3\n"
			"ro.build.user=OnePlus\n"
			"ro.build.flavor=OnePlus3-user\n"
			"ro.build.description=OnePlus3-user 7.1.1 NMF26F 136 dev-keys\n"
			"ro.common.soft=OnePlus3\n"
			"ro.display.series=OnePlus 3T\n"
			"ro.build.oemfingerprint=7.1.1/NMF26F/10122113:user/release-keys\n"
			"persist.sys.oem.region=OverSeas\n"
			"ro.build.date.Ymd=171012\n"
			"ro.build.date.ymd=171012\n"
			"ro.build.date.YmdHM=201710122300\n"
			"persist.sys.assert.panic=false\n"
			"persist.sys.assert.enable=false\n"
			"persist.sys.cfu_auto=1\n"
			"ro.build.release_type=release\n"
			"ro.build.soft.version=A.57\n"
			"ro.xxversion=v0.5\n"
			"ro.build.kernel.id=3.18-G1710122300\n"
			"persist.sys.timezone=America/New_York\n"
			"ro.build.ota.versionname=OnePlus3TOxygen_28_1710122300\n"
			"ro.build.version.ota=OnePlus3TOxygen_28.A.57_GLO_057_1710122300\n"
			"ro.build.soft.majorversion=A\n"
			"ro.product.brand=OnePlus\n"
			"ro.product.manufacturer=OnePlus\n"
			"persist.sys.kernel=yes\n"
			"persist.sys.main=yes\n"
			"persist.sys.system=yes\n"
			"persist.sys.radio=yes\n"
			"persist.sys.event=yes\n"
			"persist.sys.crash=yes\n"
			"persist.sys.qxdm=no\n"
			"debug.sf.dump.primary=true\n"
			"debug.sf.dump.external=true\n"
			"debug.sf.dump.enable=true\n"
			"debug.sf.dump=0\n"
			"persist.sys.qsee=yes\n"
			"persist.sys.tz=yes\n"
			"persist.sys.bootloader=yes\n"
			"persist.sys.pre_bootloader=yes\n"
			"persist.radio.ignore_dom_time=10\n"
			"persist.radio.rat_on=combine\n"
			"persist.radio.data_ltd_sys_ind=1\n"
			"persist.volte_enalbed_by_hw=1\n"
			"persist.radio.multisim.config=dsds\n"
			"persist.data.iwlan.enable=true\n"
			"persist.radio.start_ota_daemon=1\n"
			"persist.radio.sw_mbn_update=0\n"
			"persist.radio.hw_mbn_update=0\n"
			"ro.sys.sdcardfs=true\n"
			"# begin build properties\n"
			"# autogenerated by buildinfo.sh\n"
			"ro.build.id=NMF26F\n"
			"ro.build.version.incremental=136\n"
			"ro.build.version.sdk=25\n"
			"ro.build.version.preview_sdk=0\n"
			"ro.build.version.codename=REL\n"
			"ro.build.version.all_codenames=REL\n"
			"ro.build.version.release=7.1.1\n"
			"ro.build.version.security_patch=2017-08-01\n"
			"ro.build.version.base_os=\n"
			"ro.build.date=Thu Oct 12 22:53:06 CST 2017\n"
			"ro.build.date.utc=1507819986\n"
			"ro.build.type=user\n"
			"ro.build.host=ubuntu-64\n"
			"ro.build.tags=release-keys\n"
			"ro.product.board=QC_Reference_Phone\n"
			"# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,\n"
			"# use ro.product.cpu.abilist instead.\n"
			"ro.product.cpu.abi=arm64-v8a\n"
			"ro.product.cpu.abilist=arm64-v8a,armeabi-v7a,armeabi\n"
			"ro.product.cpu.abilist32=armeabi-v7a,armeabi\n"
			"ro.product.cpu.abilist64=arm64-v8a\n"
			"ro.product.locale=en-US\n"
			"ro.wifi.channels=\n"
			"ro.board.platform=msm8996\n"
			"# ro.build.product is obsolete; use ro.product.device\n"
			"# Do not try to parse description, fingerprint, or thumbprint\n"
			"ro.build.characteristics=nosdcard\n"
			"# end build properties\n"
			"#\n"
			"# from vendor/oneplus/config/OnePlus3/system.prop\n"
			"#\n"
			"#\n"
			"# system.prop for msm8996\n"
			"#\n"
			"\n"
			"#rild.libpath=/system/lib/libreference-ril.so\n"
			"rild.libpath=/vendor/lib64/libril-qc-qmi-1.so\n"
			"#rild.libargs=-d /dev/smd0\n"
			"persist.rild.nitz_plmn=\n"
			"persist.rild.nitz_long_ons_0=\n"
			"persist.rild.nitz_long_ons_1=\n"
			"persist.rild.nitz_long_ons_2=\n"
			"persist.rild.nitz_long_ons_3=\n"
			"persist.rild.nitz_short_ons_0=\n"
			"persist.rild.nitz_short_ons_1=\n"
			"persist.rild.nitz_short_ons_2=\n"
			"persist.rild.nitz_short_ons_3=\n"
			"ril.subscription.types=NV,RUIM\n"
			"DEVICE_PROVISIONED=1\n"
			"# Start in global mode\n"
			"#ifndef VENDOR_EDIT\n"
			"#dhj@PM, 2015/03/24, del this prop, which will be set in self-init\n"
			"#ro.telephony.default_network=10\n"
			"#endif /* VENDOR_EDIT */\n"
			"\n"
			"debug.sf.hw=1\n"
			"debug.egl.hw=1\n"
			"debug.gralloc.enable_fb_ubwc=1\n"
			"dalvik.vm.heapsize=36m\n"
			"dev.pm.dyn_samplingrate=1\n"
			"persist.demo.hdmirotationlock=false\n"
			"\n"
			"#ro.hdmi.enable=true\n"
			"#\n"
			"# system props for the cne module\n"
			"#\n"
			"persist.cne.feature=1\n"
			"\n"
			"#system prop for enabling/disabling Android XLAT\n"
			"persist.net.doxlat=false\n"
			"\n"
			"#system props for the MM modules\n"
			"media.stagefright.enable-player=true\n"
			"media.stagefright.enable-http=true\n"
			"media.stagefright.enable-aac=true\n"
			"media.stagefright.enable-qcp=true\n"
			"media.stagefright.enable-scan=true\n"
			"mmp.enable.3g2=true\n"
			"media.aac_51_output_enabled=true\n"
			"mm.enable.smoothstreaming=true\n"
			"#185971 is decimal sum of supported parsers in AAL\n"
			"#37491 is decimal sum of supported codecs in AAL\n"
			"#codecs:(PARSER_)AAC AC3 AMR_NB AMR_WB ASF AVI DTS FLV 3GP 3G2 MKV MP3 OGG QCP WAV FLAC AIFF APE MP2PS MP2TS\n"
			"#ifdef VENDOR_EDIT\n"
			"#mm.enable.qcom_parser=1048575\n"
			"#yanweibo@OnePlus.MultiMediaService, 2016/05/06,Add codecs:DIVX & DIVXHD\n"
			"#mm.enable.qcom_parser=4194303\n"
			"#lifei@OnePlus.MultiMediaService, 2016/12/13,temporary remove ogg\n"
			"mm.enable.qcom_parser=4177919\n"
			"#endif /*VENDOR_EDIT*/\n"
			"#yanweibo@onePlus.MultiMediaService,2016/12/13,Remove parser big buffer mode\n"
			"audio.parser.ip.buffer.size=0\n"
			"#endif\n"
			"persist.mm.enable.prefetch=true\n"
			"\n"
			"# Additional i/p buffer in case of encoder DCVS\n"
			"vidc.enc.dcvs.extra-buff-count=2\n"
			"\n"
			"# Set default power mode to low power for encoder\n"
			"vidc.debug.perf.mode=2\n"
			"\n"
			"# disable PQ feature by default\n"
			"vidc.enc.disable.pq=true\n"
			"\n"
			"#\n"
			"# system props for the data modules\n"
			"#\n"
			"ro.use_data_netmgrd=true\n"
			"persist.data.netmgrd.qos.enable=true\n"
			"persist.data.mode=concurrent\n"
			"\n"
			"#system props for time-services\n"
			"persist.timed.enable=true\n"
			"\n"
			"#\n"
			"# system prop for opengles version\n"
			"#\n"
			"# 196608 is decimal for 0x30000 to report version 3.0\n"
			"# 196609 is decimal for 0x30001 to report version 3.1\n"
			"# 196610 is decimal for 0x30002 to report version 3.2\n"
			"ro.opengles.version=196610\n"
			"\n"
			"# system property for maximum number of HFP client connections\n"
			"bt.max.hfpclient.connections=1\n"
			"\n"
			"# System property for cabl\n"
			"#ifdef VENDOR_EDIT\n"
			"#yankelong ,2016/11/29 ,to disable cabl function\n"
			"#ro.qualcomm.cabl=2\n"
			"ro.qualcomm.cabl=0\n"
			"#endif /*VENDOR_EDIT*/\n"
			"\n"
			"#\n"
			"# System props for telephony\n"
			"# System prop to turn on CdmaLTEPhone always\n"
			"#ifdef VENDOR_EDIT\n"
			"#dhj@PM, 2015-12-23, set this prop in self-init.c, only cdma mobile set it\n"
			"#telephony.lteOnCdmaDevice=1\n"
			"#endif /*VENDOR_EDIT*/\n"
			"\n"
			"#Simulate sdcard on /data/media\n"
			"#\n"
			"persist.fuse_sdcard=true\n"
			"\n"
			"#system prop for Bluetooth SOC type\n"
			"qcom.bluetooth.soc=rome\n"
			"\n"
			"#system prop for wipower support\n"
			"ro.bluetooth.wipower=true\n"
			"\n"
			"#Set this true as ROME which is programmed\n"
			"#as embedded wipower mode by deafult\n"
			"ro.bluetooth.emb_wp_mode=true\n"
			"\n"
			"#\n"
			"#snapdragon value add features\n"
			"#\n"
			"##fluencetype can be \"fluence\" or \"fluencepro\" or \"none\"\n"
			"#ifdef VENDOR_EDIT\n"
			"#/*zhiguang.su@MultiMedia.AudioDrv , 2015/11/02, change for 15801*/\n"
			"#ro.qc.sdk.audio.fluencetype=none\n"
			"ro.qc.sdk.audio.fluencetype=fluence\n"
			"#endif\n"
			"\n"
			"#system prop for RmNet Data\n"
			"persist.rmnet.data.enable=true\n"
			"persist.data.wda.enable=true\n"
			"persist.data.df.dl_mode=5\n"
			"persist.data.df.ul_mode=5\n"
			"persist.data.df.agg.dl_pkt=10\n"
			"persist.data.df.agg.dl_size=4096\n"
			"persist.data.df.mux_count=8\n"
			"persist.data.df.iwlan_mux=9\n"
			"persist.data.df.dev_name=rmnet_usb0\n"
			"\n"
			"#property to enable user to access Google WFD settings\n"
			"persist.debug.wfd.enable=1\n"
			"##property to choose between virtual/external wfd display\n"
			"persist.sys.wfd.virtual=0\n"
			"\n"
			"#property to enable sde downscale feature for external display\n"
			"#sdm.debug.downscale_external=1\n"
			"\n"
			"#property to specify the number of frames to skip before setting hint\n"
			"sdm.perf_hint_window=50\n"
			"\n"
			"# system prop for NFC DT\n"
			"ro.nfc.port=I2C\n"
			"\n"
			"#property to enable WFD WL solution\n"
			"ro.vendor.wl_library=libqti-wl.so\n"
			"\n"
			"#property for vendor specific library\n"
			"ro.vendor.gt_library=libqti-gt.so\n"
			"ro.vendor.at_library=libqti-at.so\n"
			"sys.games.gt.prof=1\n"
			"\n"
			"#ifdef VENDOR_EDIT\n"
			"#xiaoxiaohuan@OnePlus.MultiMediaService,2016/10/17, porting hwui parameters to N\n"
			"#hwui properties\n"
			"ro.hwui.texture_cache_size=96\n"
			"ro.hwui.layer_cache_size=64\n"
			"ro.hwui.r_buffer_cache_size=12\n"
			"ro.hwui.path_cache_size=39\n"
			"ro.hwui.gradient_cache_size=1\n"
			"ro.hwui.drop_shadow_cache_size=7\n"
			"ro.hwui.texture_cache_flushrate=0.4\n"
			"ro.hwui.text_small_cache_width=2048\n"
			"ro.hwui.text_small_cache_height=2048\n"
			"ro.hwui.text_large_cache_width=3072\n"
			"ro.hwui.text_large_cache_height=2048\n"
			"#else\n"
			"#ro.hwui.texture_cache_size=72\n"
			"#ro.hwui.layer_cache_size=48\n"
			"#ro.hwui.r_buffer_cache_size=8\n"
			"#ro.hwui.path_cache_size=32\n"
			"#ro.hwui.gradient_cache_size=1\n"
			"#ro.hwui.drop_shadow_cache_size=6\n"
			"#ro.hwui.texture_cache_flushrate=0.4\n"
			"#ro.hwui.text_small_cache_width=1024\n"
			"#ro.hwui.text_small_cache_height=1024\n"
			"#ro.hwui.text_large_cache_width=2048\n"
			"#ro.hwui.text_large_cache_height=1024\n"
			"#endif\n"
			"\n"
			"#ifdef VENDOR_EDIT\n"
			"#lifei@mediaserver enable multiple offload\n"
			"audio.offload.multiple.enabled=true\n"
			"\n"
			"#Disable property for Dolby ds2\n"
			"audio.dolby.ds2.enabled=false\n"
			"\n"
			"#Disable property for hard bypass\n"
			"audio.dolby.ds2.hardbypass=false\n"
			"\n"
			"audio.offload.passthrough=false\n"
			"\n"
			"#guoguangyi@multimedia,Oct/20/2016,fixs online video block\n"
			"#audio data too little to support offload playing\n"
			"audio.offload.pcm.16bit.enable=false\n"
			"#endif\n"
			"\n"
			"#ifdef VENDOR_EDIT\n"
			"#xiaoxiaohuan@OnePlus.MultiMediaService, 2016/11/22\n"
			"ro.am.reschedule_service=true\n"
			"#endif/*VENDOR_EDIT*/\n"
			"\n"
			"#ifndef VENDOR_EDIT\n"
			"#jayfan, 2016/10/18,, Modify for enable hardware keys\n"
			"#qemu.hw.mainkeys=0\n"
			"#else\n"
			"qemu.hw.mainkeys=1\n"
			"#endif\n"
			"\n"
			"#property to enable VDS WFD solution\n"
			"persist.hwc.enable_vds=1\n"
			"\n"
			"#Enable stm events\n"
			"persist.debug.coresight.config=stm-events\n"
			"#property to enable fingerprint\n"
			"persist.qfp=false\n"
			"\n"
			"#default pd_enable value\n"
			"persist.sys.pd_enable=0\n"
			"#Disable rotator split feature\n"
			"sdm.debug.disable_rotator_split=1\n"
			"\n"
			"#Increase cached app limit\n"
			"ro.sys.fw.bg_apps_limit=32\n"
			"\n"
			"#Camera fullscreen doesn't show navigation bar\n"
			"Camera.no_navigation_bar=true\n"
			"\n"
			"#ifdef VENDOR_EDIT\n"
			"#yangfb 20160919 ,modify to set cutoff voltage to 3250mv\n"
			"ro.cutoff_voltage_mv=3250\n"
			"#endif\n"
			"\n"
			"#property for game detection feature\n"
			"debug.enable.gamed=0\n"
			"#ifdef VENDOR_EDIT\n"
			"#lifei@OnLineRD.MultiMediaService, 2015/12/23, Modify for support offload Is greater than 30s Audio source\n"
			"audio.offload.min.duration.secs=30\n"
			"#endif\n"
			"\n"
			"#Disable face beautification\n"
			"persist.ts.postmakeup=false\n"
			"persist.ts.rtmakeup=false\n"
			"\n"
			"#Enable device orientation sensor\n"
			"ro.qti.sensors.dev_ori=false\n"
			"ro.qti.sensors.pmd=false\n"
			"ro.qti.sensors.sta_detect=false\n"
			"ro.qti.sensors.mot_detect=false\n"
			"\n"
			"#ifdef VENDOR_EDIT\n"
			"#Enable Dual SIM feature\n"
			"persist.radio.multisim.config=dsds\n"
			"#mbn config\n"
			"persist.radio.hw_mbn_update=0\n"
			"persist.radio.sw_mbn_update=0\n"
			"persist.radio.start_ota_daemon=1\n"
			"#endif\n"
			"\n"
			"#ifdef VENDOR_EDIT\n"
			"#lifei@OnLineRD.MultiMediaService, 2016/03/22, Modify for support Dirac Audio source\n"
			"persist.dirac.acs.controller=qem\n"
			"#endif\n"
			"\n"
			"#ifdef VENDOR_EDIT\n"
			"persist.dbg.ims_volte_enable=0\n"
			"persist.dbg.volte_avail_ovr=0\n"
			"persist.dbg.vt_avail_ovr=0\n"
			"persist.data.iwlan.enable=true\n"
			"persist.dbg.wfc_avail_ovr=0\n"
			"#endif\n"
			"\n"
			"#ifdef VENDOR_EDIT\n"
			"persist.radio.enhance_ecall=true\n"
			"#endif\n"
			"\n"
			"#ifdef VENDOR_EDIT\n"
			"#enable signal cheating\n"
			"persist.sys.oem_smooth=1\n"
			"#endif /*VENDOR_EDIT*/\n"
			"\n"
			"#ifdef VENDOR_EDIT\n"
			"# system props for the cne module #\n"
			"# 4  enable NSRM adb root\n"
			"# 1  Only CnE is enabled; NSRM, FMC, and WQE are disabled\n"
			"# 0  Disables\n"
			"persist.dpm.feature=11\n"
			"#endif\n"
			"#Expose aux camera for below packages\n"
			"camera.aux.packagelist=org.codeaurora.snapcam\n"
			"\n"
			"#\n"
			"# ADDITIONAL_BUILD_PROPERTIES\n"
			"#\n"
			"ro.product.first_api_level=23\n"
			"dalvik.vm.heapstartsize=16m\n"
			"dalvik.vm.heapgrowthlimit=256m\n"
			"dalvik.vm.heapsize=512m\n"
			"dalvik.vm.heaptargetutilization=0.75\n"
			"dalvik.vm.heapminfree=4m\n"
			"dalvik.vm.heapmaxfree=8m\n"
			"keyguard.no_require_sim=true\n"
			"ro.com.android.dataroaming=false\n"
			"ro.config.ringtone=oneplus_tune.ogg\n"
			"ro.config.mms_notification=free.ogg\n"
			"ro.config.notification_sound=meet.ogg\n"
			"ro.config.alarm_alert=spring.ogg\n"
			"ro.carrier=unknown\n"
			"ro.vendor.extension_library=libqti-perfd-client.so\n"
			"persist.radio.apm_sim_not_pwdn=1\n"
			"persist.radio.sib16_support=1\n"
			"persist.radio.custom_ecc=1\n"
			"persist.radio.multisim.config=dsds\n"
			"ro.frp.pst=/dev/block/bootdevice/by-name/frp\n"
			"ro.setupwizard.mode=OPTIONAL\n"
			"ro.com.google.gmsversion=7.1_r4\n"
			"drm.service.enabled=true\n"
			"audio_hal.period_size=192\n"
			"ro.qc.sdk.audio.fluencetype=none\n"
			"persist.audio.fluence.voicecall=true\n"
			"persist.audio.fluence.voicerec=false\n"
			"persist.audio.fluence.speaker=true\n"
			"tunnel.audio.encode=false\n"
			"audio.offload.buffer.size.kb=64\n"
			"audio.offload.video=false\n"
			"audio.offload.pcm.16bit.enable=false\n"
			"audio.offload.pcm.24bit.enable=true\n"
			"audio.offload.track.enable=false\n"
			"audio.deep_buffer.media=true\n"
			"media.stagefright.audio.sink=280\n"
			"use.voice.path.for.pcm.voip=true\n"
			"audio.offload.multiaac.enable=true\n"
			"audio.dolby.ds2.enabled=false\n"
			"audio.dolby.ds2.hardbypass=false\n"
			"audio.offload.multiple.enabled=true\n"
			"audio.offload.passthrough=false\n"
			"ro.qc.sdk.audio.ssr=false\n"
			"audio.offload.gapless.enabled=true\n"
			"audio.safx.pbe.enabled=true\n"
			"audio.parser.ip.buffer.size=0\n"
			"qcom.hw.aac.encoder=true\n"
			"use.qti.sw.alac.decoder=true\n"
			"use.qti.sw.ape.decoder=true\n"
			"flac.sw.decoder.24bit.support=true\n"
			"af.fast_track_multiplier=2\n"
			"camera.disable_zsl_mode=1\n"
			"persist.sys.dalvik.vm.lib.2=libart.so\n"
			"dalvik.vm.isa.arm64.variant=kryo\n"
			"dalvik.vm.isa.arm64.features=default\n"
			"dalvik.vm.isa.arm.variant=cortex-a53\n"
			"dalvik.vm.isa.arm.features=default\n"
			"net.bt.name=Android\n"
			"dalvik.vm.stack-trace-file=/data/anr/traces.txt\n"
			"oplib.oneplus_sdk_utils=0.1.2\n"
			"oplib.oneplus_sdk_wrapper=0.1.0\n"
			"ro.mdtp.package_name2=com.qualcomm.qti.securemsm.mdtp.MdtpDemo\n"
			"ro.expect.recovery_id=0x38e644b768c30cbec99fead9e0b227c97264a49f000000000000000000000000\n",
	},
	{
		.path = "/sys/devices/system/cpu/kernel_max",
		.size = 2,
		.content = "3\n",
	},
	{
		.path = "/sys/devices/system/cpu/possible",
		.size = 4,
		.content = "0-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/present",
		.size = 4,
		.content = "0-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/online",
		.size = 4,
		.content = "0-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/offline",
		.size = 1,
		.content = "\n",
	},
	{
		.path = "/sys/devices/system/cpu/modalias",
		.size = 66,
		.content = "cpu:type:aarch64:feature:,0000,0001,0002,0003,0004,0005,0006,0007\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpufreq/all_time_in_state",
		.size = 31,
		.content = "freq\t\tcpu0\t\tcpu1\t\tcpu2\t\tcpu3\t\t\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpufreq/current_in_state",
		.size = 532,
		.content =
			"CPU2:307200=0 384000=0 460800=0 537600=0 614400=0 691200=0 748800=0 825600=0 902400=0 979200=0 1056000=0 1132800=0 1209600=0 1286400=0 1363200=0 1440000=0 1516800=0 1593600=0 1670400=0 1747200=0 1824000=0 1900800=0 1977600=0 2054400=0 2150400=0 2246400=0 2342400=0 \n"
			"CPU3:307200=0 384000=0 460800=0 537600=0 614400=0 691200=0 748800=0 825600=0 902400=0 979200=0 1056000=0 1132800=0 1209600=0 1286400=0 1363200=0 1440000=0 1516800=0 1593600=0 1670400=0 1747200=0 1824000=0 1900800=0 1977600=0 2054400=0 2150400=0 2246400=0 2342400=0 \n",
	},
	{
		.path = "/sys/devices/system/cpu/cpuidle/current_driver",
		.size = 9,
		.content = "msm_idle\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpuidle/current_governor_ro",
		.size = 5,
		.content = "qcom\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpuidle/driver/name",
		.size = 9,
		.content = "msm_idle\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/affected_cpus",
		.size = 4,
		.content = "0 1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq",
		.size = 8,
		.content = "2188800\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq",
		.size = 7,
		.content = "307200\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_transition_latency",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/related_cpus",
		.size = 4,
		.content = "0 1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies",
		.size = 143,
		.content = "307200 384000 460800 537600 614400 691200 768000 844800 902400 979200 1056000 1132800 1209600 1286400 1363200 1440000 1516800 1593600 2188800 \n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors",
		.size = 67,
		.content = "interactive conservative ondemand userspace powersave performance \n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq",
		.size = 7,
		.content = "307200\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/scaling_driver",
		.size = 4,
		.content = "msm\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor",
		.size = 12,
		.content = "interactive\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq",
		.size = 7,
		.content = "307200\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state",
		.size = 210,
		.content =
			"307200 1922\n"
			"384000 56\n"
			"460800 16\n"
			"537600 14\n"
			"614400 20\n"
			"691200 20\n"
			"768000 19\n"
			"844800 19\n"
			"902400 17\n"
			"979200 278\n"
			"1056000 52\n"
			"1132800 17\n"
			"1209600 243\n"
			"1286400 127\n"
			"1363200 127\n"
			"1440000 166\n"
			"1516800 249\n"
			"1593600 966\n"
			"2188800 1454\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/cpufreq/stats/total_trans",
		.size = 4,
		.content = "499\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/core_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/core_siblings",
		.size = 2,
		.content = "3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/core_siblings_list",
		.size = 4,
		.content = "0-1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/physical_package_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/thread_siblings",
		.size = 2,
		.content = "1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu0/topology/thread_siblings_list",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/cpuidle/driver/name",
		.size = 9,
		.content = "msm_idle\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/cpufreq/affected_cpus",
		.size = 4,
		.content = "0 1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/cpufreq/cpuinfo_max_freq",
		.size = 8,
		.content = "2188800\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/cpufreq/cpuinfo_min_freq",
		.size = 7,
		.content = "307200\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/cpufreq/cpuinfo_transition_latency",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/cpufreq/related_cpus",
		.size = 4,
		.content = "0 1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/cpufreq/scaling_available_frequencies",
		.size = 143,
		.content = "307200 384000 460800 537600 614400 691200 768000 844800 902400 979200 1056000 1132800 1209600 1286400 1363200 1440000 1516800 1593600 2188800 \n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/cpufreq/scaling_available_governors",
		.size = 67,
		.content = "interactive conservative ondemand userspace powersave performance \n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/cpufreq/scaling_cur_freq",
		.size = 7,
		.content = "307200\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/cpufreq/scaling_driver",
		.size = 4,
		.content = "msm\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/cpufreq/scaling_governor",
		.size = 12,
		.content = "interactive\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq",
		.size = 7,
		.content = "307200\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/cpufreq/stats/time_in_state",
		.size = 210,
		.content =
			"307200 2103\n"
			"384000 58\n"
			"460800 16\n"
			"537600 14\n"
			"614400 20\n"
			"691200 20\n"
			"768000 21\n"
			"844800 19\n"
			"902400 19\n"
			"979200 291\n"
			"1056000 55\n"
			"1132800 19\n"
			"1209600 243\n"
			"1286400 127\n"
			"1363200 127\n"
			"1440000 166\n"
			"1516800 249\n"
			"1593600 973\n"
			"2188800 1454\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/cpufreq/stats/total_trans",
		.size = 4,
		.content = "512\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/topology/core_id",
		.size = 2,
		.content = "1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/topology/core_siblings",
		.size = 2,
		.content = "3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/topology/core_siblings_list",
		.size = 4,
		.content = "0-1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/topology/physical_package_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/topology/thread_siblings",
		.size = 2,
		.content = "2\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu1/topology/thread_siblings_list",
		.size = 2,
		.content = "1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpuidle/driver/name",
		.size = 9,
		.content = "msm_idle\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpufreq/affected_cpus",
		.size = 4,
		.content = "2 3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpufreq/cpuinfo_max_freq",
		.size = 8,
		.content = "2342400\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpufreq/cpuinfo_min_freq",
		.size = 7,
		.content = "307200\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpufreq/cpuinfo_transition_latency",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpufreq/related_cpus",
		.size = 4,
		.content = "2 3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpufreq/scaling_available_frequencies",
		.size = 207,
		.content = "307200 384000 460800 537600 614400 691200 748800 825600 902400 979200 1056000 1132800 1209600 1286400 1363200 1440000 1516800 1593600 1670400 1747200 1824000 1900800 1977600 2054400 2150400 2246400 2342400 \n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpufreq/scaling_available_governors",
		.size = 67,
		.content = "interactive conservative ondemand userspace powersave performance \n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpufreq/scaling_cur_freq",
		.size = 7,
		.content = "307200\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpufreq/scaling_driver",
		.size = 4,
		.content = "msm\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpufreq/scaling_governor",
		.size = 12,
		.content = "interactive\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq",
		.size = 8,
		.content = "2342400\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq",
		.size = 7,
		.content = "307200\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpufreq/stats/time_in_state",
		.size = 292,
		.content =
			"307200 1897\n"
			"384000 22\n"
			"460800 6\n"
			"537600 9\n"
			"614400 15\n"
			"691200 6\n"
			"748800 4\n"
			"825600 13\n"
			"902400 10\n"
			"979200 13\n"
			"1056000 13\n"
			"1132800 5\n"
			"1209600 6\n"
			"1286400 283\n"
			"1363200 22\n"
			"1440000 23\n"
			"1516800 48\n"
			"1593600 29\n"
			"1670400 33\n"
			"1747200 111\n"
			"1824000 102\n"
			"1900800 100\n"
			"1977600 98\n"
			"2054400 192\n"
			"2150400 435\n"
			"2246400 296\n"
			"2342400 1952\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/cpufreq/stats/total_trans",
		.size = 4,
		.content = "499\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/topology/core_id",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/topology/core_siblings",
		.size = 2,
		.content = "c\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/topology/core_siblings_list",
		.size = 4,
		.content = "2-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/topology/physical_package_id",
		.size = 2,
		.content = "1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/topology/thread_siblings",
		.size = 2,
		.content = "4\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu2/topology/thread_siblings_list",
		.size = 2,
		.content = "2\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/cpuidle/driver/name",
		.size = 9,
		.content = "msm_idle\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/cpufreq/affected_cpus",
		.size = 4,
		.content = "2 3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/cpufreq/cpuinfo_max_freq",
		.size = 8,
		.content = "2342400\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/cpufreq/cpuinfo_min_freq",
		.size = 7,
		.content = "307200\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/cpufreq/cpuinfo_transition_latency",
		.size = 2,
		.content = "0\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/cpufreq/related_cpus",
		.size = 4,
		.content = "2 3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/cpufreq/scaling_available_frequencies",
		.size = 207,
		.content = "307200 384000 460800 537600 614400 691200 748800 825600 902400 979200 1056000 1132800 1209600 1286400 1363200 1440000 1516800 1593600 1670400 1747200 1824000 1900800 1977600 2054400 2150400 2246400 2342400 \n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/cpufreq/scaling_available_governors",
		.size = 67,
		.content = "interactive conservative ondemand userspace powersave performance \n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/cpufreq/scaling_cur_freq",
		.size = 7,
		.content = "307200\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/cpufreq/scaling_driver",
		.size = 4,
		.content = "msm\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/cpufreq/scaling_governor",
		.size = 12,
		.content = "interactive\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq",
		.size = 8,
		.content = "2342400\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq",
		.size = 7,
		.content = "307200\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/cpufreq/stats/time_in_state",
		.size = 292,
		.content =
			"307200 2074\n"
			"384000 24\n"
			"460800 6\n"
			"537600 9\n"
			"614400 17\n"
			"691200 6\n"
			"748800 4\n"
			"825600 13\n"
			"902400 10\n"
			"979200 13\n"
			"1056000 15\n"
			"1132800 5\n"
			"1209600 8\n"
			"1286400 289\n"
			"1363200 24\n"
			"1440000 23\n"
			"1516800 54\n"
			"1593600 29\n"
			"1670400 33\n"
			"1747200 111\n"
			"1824000 102\n"
			"1900800 100\n"
			"1977600 98\n"
			"2054400 192\n"
			"2150400 435\n"
			"2246400 296\n"
			"2342400 1952\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/cpufreq/stats/total_trans",
		.size = 4,
		.content = "514\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/topology/core_id",
		.size = 2,
		.content = "1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/topology/core_siblings",
		.size = 2,
		.content = "c\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/topology/core_siblings_list",
		.size = 4,
		.content = "2-3\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/topology/physical_package_id",
		.size = 2,
		.content = "1\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/topology/thread_siblings",
		.size = 2,
		.content = "8\n",
	},
	{
		.path = "/sys/devices/system/cpu/cpu3/topology/thread_siblings_list",
		.size = 2,
		.content = "3\n",
	},
	{ NULL },
};
#ifdef __ANDROID__
struct cpuinfo_mock_property properties[] = {
	{
		.key = "Camera.no_navigation_bar",
		.value = "true",
	},
	{
		.key = "DEVICE_PROVISIONED",
		.value = "1",
	},
	{
		.key = "af.fast_track_multiplier",
		.value = "2",
	},
	{
		.key = "audio.deep_buffer.media",
		.value = "true",
	},
	{
		.key = "audio.dolby.ds2.enabled",
		.value = "false",
	},
	{
		.key = "audio.dolby.ds2.hardbypass",
		.value = "false",
	},
	{
		.key = "audio.offload.buffer.size.kb",
		.value = "64",
	},
	{
		.key = "audio.offload.gapless.enabled",
		.value = "true",
	},
	{
		.key = "audio.offload.min.duration.secs",
		.value = "30",
	},
	{
		.key = "audio.offload.multiaac.enable",
		.value = "true",
	},
	{
		.key = "audio.offload.multiple.enabled",
		.value = "true",
	},
	{
		.key = "audio.offload.passthrough",
		.value = "false",
	},
	{
		.key = "audio.offload.pcm.16bit.enable",
		.value = "false",
	},
	{
		.key = "audio.offload.pcm.24bit.enable",
		.value = "true",
	},
	{
		.key = "audio.offload.track.enable",
		.value = "false",
	},
	{
		.key = "audio.offload.video",
		.value = "false",
	},
	{
		.key = "audio.parser.ip.buffer.size",
		.value = "0",
	},
	{
		.key = "audio.safx.pbe.enabled",
		.value = "true",
	},
	{
		.key = "audio_hal.period_size",
		.value = "192",
	},
	{
		.key = "bt.max.hfpclient.connections",
		.value = "1",
	},
	{
		.key = "camera.aux.packagelist",
		.value = "org.codeaurora.snapcam",
	},
	{
		.key = "camera.disable_zsl_mode",
		.value = "1",
	},
	{
		.key = "dalvik.vm.appimageformat",
		.value = "lz4",
	},
	{
		.key = "dalvik.vm.dex2oat-Xms",
		.value = "64m",
	},
	{
		.key = "dalvik.vm.dex2oat-Xmx",
		.value = "512m",
	},
	{
		.key = "dalvik.vm.heapgrowthlimit",
		.value = "256m",
	},
	{
		.key = "dalvik.vm.heapmaxfree",
		.value = "8m",
	},
	{
		.key = "dalvik.vm.heapminfree",
		.value = "4m",
	},
	{
		.key = "dalvik.vm.heapsize",
		.value = "512m",
	},
	{
		.key = "dalvik.vm.heapstartsize",
		.value = "16m",
	},
	{
		.key = "dalvik.vm.heaptargetutilization",
		.value = "0.75",
	},
	{
		.key = "dalvik.vm.image-dex2oat-Xms",
		.value = "64m",
	},
	{
		.key = "dalvik.vm.image-dex2oat-Xmx",
		.value = "64m",
	},
	{
		.key = "dalvik.vm.isa.arm.features",
		.value = "default",
	},
	{
		.key = "dalvik.vm.isa.arm.variant",
		.value = "cortex-a53",
	},
	{
		.key = "dalvik.vm.isa.arm64.features",
		.value = "default",
	},
	{
		.key = "dalvik.vm.isa.arm64.variant",
		.value = "kryo",
	},
	{
		.key = "dalvik.vm.stack-trace-file",
		.value = "/data/anr/traces.txt",
	},
	{
		.key = "dalvik.vm.usejit",
		.value = "true",
	},
	{
		.key = "dalvik.vm.usejitprofiles",
		.value = "true",
	},
	{
		.key = "debug.atrace.tags.enableflags",
		.value = "0",
	},
	{
		.key = "debug.egl.hw",
		.value = "1",
	},
	{
		.key = "debug.enable.gamed",
		.value = "0",
	},
	{
		.key = "debug.force_rtl",
		.value = "0",
	},
	{
		.key = "debug.gralloc.enable_fb_ubwc",
		.value = "1",
	},
	{
		.key = "debug.gralloc.gfx_ubwc_disable",
		.value = "0",
	},
	{
		.key = "debug.sf.dump",
		.value = "0",
	},
	{
		.key = "debug.sf.dump.enable",
		.value = "true",
	},
	{
		.key = "debug.sf.dump.external",
		.value = "true",
	},
	{
		.key = "debug.sf.dump.primary",
		.value = "true",
	},
	{
		.key = "debug.sf.hw",
		.value = "1",
	},
	{
		.key = "dev.bootcomplete",
		.value = "1",
	},
	{
		.key = "dev.pm.dyn_samplingrate",
		.value = "1",
	},
	{
		.key = "drm.service.enabled",
		.value = "true",
	},
	{
		.key = "flac.sw.decoder.24bit.support",
		.value = "true",
	},
	{
		.key = "gsm.current.phone-type",
		.value = "1,1",
	},
	{
		.key = "gsm.network.type",
		.value = "Unknown,Unknown",
	},
	{
		.key = "gsm.operator.alpha",
		.value = "",
	},
	{
		.key = "gsm.operator.iso-country",
		.value = "",
	},
	{
		.key = "gsm.operator.isroaming",
		.value = "false,false",
	},
	{
		.key = "gsm.operator.numeric",
		.value = "",
	},
	{
		.key = "gsm.sim.operator.alpha",
		.value = ",",
	},
	{
		.key = "gsm.sim.operator.iso-country",
		.value = ",",
	},
	{
		.key = "gsm.sim.operator.numeric",
		.value = ",",
	},
	{
		.key = "gsm.sim.state",
		.value = "ABSENT,ABSENT",
	},
	{
		.key = "gsm.version.baseband",
		.value = "MPSS.TH.2.0.c1.9-00102-M8996FAAAANAZM-1.89286.1.99649.1",
	},
	{
		.key = "gsm.version.baseband1",
		.value = "MPSS.TH.2.0.c1.9-00102-M8996FAAAANAZM-1.89286.1.99649.1",
	},
	{
		.key = "gsm.version.ril-impl",
		.value = "Qualcomm RIL 1.0",
	},
	{
		.key = "init.svc.OPNetlinkService",
		.value = "running",
	},
	{
		.key = "init.svc.RIDL",
		.value = "stopped",
	},
	{
		.key = "init.svc.adbd",
		.value = "running",
	},
	{
		.key = "init.svc.adsprpcd",
		.value = "running",
	},
	{
		.key = "init.svc.atfwd",
		.value = "running",
	},
	{
		.key = "init.svc.audiod",
		.value = "running",
	},
	{
		.key = "init.svc.audioserver",
		.value = "running",
	},
	{
		.key = "init.svc.bootanim",
		.value = "stopped",
	},
	{
		.key = "init.svc.cameraserver",
		.value = "running",
	},
	{
		.key = "init.svc.clear-bcb",
		.value = "stopped",
	},
	{
		.key = "init.svc.cnd",
		.value = "running",
	},
	{
		.key = "init.svc.cnss-daemon",
		.value = "running",
	},
	{
		.key = "init.svc.cnss_diag",
		.value = "stopped",
	},
	{
		.key = "init.svc.config_bluetooth",
		.value = "stopped",
	},
	{
		.key = "init.svc.config_bt_addr",
		.value = "stopped",
	},
	{
		.key = "init.svc.dashd",
		.value = "running",
	},
	{
		.key = "init.svc.debuggerd",
		.value = "running",
	},
	{
		.key = "init.svc.debuggerd64",
		.value = "running",
	},
	{
		.key = "init.svc.diag_mdlog_stop",
		.value = "stopped",
	},
	{
		.key = "init.svc.dpmd",
		.value = "running",
	},
	{
		.key = "init.svc.drm",
		.value = "running",
	},
	{
		.key = "init.svc.energy-awareness",
		.value = "stopped",
	},
	{
		.key = "init.svc.engineermode-sh",
		.value = "stopped",
	},
	{
		.key = "init.svc.fingerprintd",
		.value = "running",
	},
	{
		.key = "init.svc.flash_recovery",
		.value = "stopped",
	},
	{
		.key = "init.svc.gatekeeperd",
		.value = "running",
	},
	{
		.key = "init.svc.healthd",
		.value = "running",
	},
	{
		.key = "init.svc.ifaadaemon",
		.value = "running",
	},
	{
		.key = "init.svc.imsdatadaemon",
		.value = "running",
	},
	{
		.key = "init.svc.imsqmidaemon",
		.value = "running",
	},
	{
		.key = "init.svc.installd",
		.value = "running",
	},
	{
		.key = "init.svc.iop",
		.value = "running",
	},
	{
		.key = "init.svc.ipacm",
		.value = "running",
	},
	{
		.key = "init.svc.ipacm-diag",
		.value = "running",
	},
	{
		.key = "init.svc.irsc_util",
		.value = "stopped",
	},
	{
		.key = "init.svc.keystore",
		.value = "running",
	},
	{
		.key = "init.svc.leak_service",
		.value = "stopped",
	},
	{
		.key = "init.svc.lmkd",
		.value = "running",
	},
	{
		.key = "init.svc.loc_launcher",
		.value = "running",
	},
	{
		.key = "init.svc.logd",
		.value = "running",
	},
	{
		.key = "init.svc.logd-reinit",
		.value = "stopped",
	},
	{
		.key = "init.svc.mdm_launcher",
		.value = "stopped",
	},
	{
		.key = "init.svc.mdtpd",
		.value = "running",
	},
	{
		.key = "init.svc.media",
		.value = "running",
	},
	{
		.key = "init.svc.mediacodec",
		.value = "running",
	},
	{
		.key = "init.svc.mediadrm",
		.value = "running",
	},
	{
		.key = "init.svc.mediaextractor",
		.value = "running",
	},
	{
		.key = "init.svc.netd",
		.value = "running",
	},
	{
		.key = "init.svc.netmgrd",
		.value = "running",
	},
	{
		.key = "init.svc.oem_audio_device",
		.value = "stopped",
	},
	{
		.key = "init.svc.oem_early_boot",
		.value = "stopped",
	},
	{
		.key = "init.svc.oemlogkit",
		.value = "running",
	},
	{
		.key = "init.svc.p2p_supplicant",
		.value = "running",
	},
	{
		.key = "init.svc.per_mgr",
		.value = "running",
	},
	{
		.key = "init.svc.per_proxy",
		.value = "running",
	},
	{
		.key = "init.svc.perfd",
		.value = "running",
	},
	{
		.key = "init.svc.port-bridge",
		.value = "running",
	},
	{
		.key = "init.svc.ppd",
		.value = "running",
	},
	{
		.key = "init.svc.qcamerasvr",
		.value = "running",
	},
	{
		.key = "init.svc.qcom-c_core-sh",
		.value = "stopped",
	},
	{
		.key = "init.svc.qcom-c_main-sh",
		.value = "stopped",
	},
	{
		.key = "init.svc.qcom-post-boot",
		.value = "stopped",
	},
	{
		.key = "init.svc.qcom-sh",
		.value = "stopped",
	},
	{
		.key = "init.svc.qcom-usb-sh",
		.value = "stopped",
	},
	{
		.key = "init.svc.qfp-daemon",
		.value = "running",
	},
	{
		.key = "init.svc.qseecomd",
		.value = "running",
	},
	{
		.key = "init.svc.qseeproxydaemon",
		.value = "running",
	},
	{
		.key = "init.svc.qti",
		.value = "running",
	},
	{
		.key = "init.svc.qti-testscripts",
		.value = "stopped",
	},
	{
		.key = "init.svc.qvop-daemon",
		.value = "running",
	},
	{
		.key = "init.svc.remosaic_daemon",
		.value = "running",
	},
	{
		.key = "init.svc.ril-daemon",
		.value = "running",
	},
	{
		.key = "init.svc.ril-daemon2",
		.value = "running",
	},
	{
		.key = "init.svc.rmt_storage",
		.value = "running",
	},
	{
		.key = "init.svc.seempd",
		.value = "running",
	},
	{
		.key = "init.svc.self-init",
		.value = "stopped",
	},
	{
		.key = "init.svc.sensor-sh",
		.value = "stopped",
	},
	{
		.key = "init.svc.sensors",
		.value = "running",
	},
	{
		.key = "init.svc.servicemanager",
		.value = "running",
	},
	{
		.key = "init.svc.smartadjust",
		.value = "running",
	},
	{
		.key = "init.svc.surfaceflinger",
		.value = "running",
	},
	{
		.key = "init.svc.tftp_server",
		.value = "running",
	},
	{
		.key = "init.svc.thermal-engine",
		.value = "running",
	},
	{
		.key = "init.svc.time_daemon",
		.value = "running",
	},
	{
		.key = "init.svc.ueventd",
		.value = "running",
	},
	{
		.key = "init.svc.usf-post-boot",
		.value = "stopped",
	},
	{
		.key = "init.svc.usf_proximity",
		.value = "running",
	},
	{
		.key = "init.svc.vold",
		.value = "running",
	},
	{
		.key = "init.svc.zygote",
		.value = "running",
	},
	{
		.key = "init.svc.zygote_secondary",
		.value = "running",
	},
	{
		.key = "keyguard.no_require_sim",
		.value = "true",
	},
	{
		.key = "log.tag.BeamManager",
		.value = "INFO",
	},
	{
		.key = "log.tag.BeamShareActivity",
		.value = "INFO",
	},
	{
		.key = "log.tag.BluetoothHidDev",
		.value = "INFO",
	},
	{
		.key = "log.tag.BluetoothHidHost",
		.value = "INFO",
	},
	{
		.key = "log.tag.BluetoothMap",
		.value = "INFO",
	},
	{
		.key = "log.tag.BluetoothOpp",
		.value = "INFO",
	},
	{
		.key = "log.tag.BluetoothPan",
		.value = "INFO",
	},
	{
		.key = "log.tag.BluetoothPbap",
		.value = "INFO",
	},
	{
		.key = "log.tag.BluetoothSap",
		.value = "INFO",
	},
	{
		.key = "log.tag.BluetoothSocket",
		.value = "INFO",
	},
	{
		.key = "log.tag.DockService",
		.value = "INFO",
	},
	{
		.key = "log.tag.ForegroundUtils",
		.value = "INFO",
	},
	{
		.key = "log.tag.GNPProxy",
		.value = "INFO",
	},
	{
		.key = "log.tag.GeofenceManager",
		.value = "INFO",
	},
	{
		.key = "log.tag.GmsNetworkLocationProvi",
		.value = "INFO",
	},
	{
		.key = "log.tag.GnssLocationProvider",
		.value = "INFO",
	},
	{
		.key = "log.tag.GpsXtraDownloader",
		.value = "INFO",
	},
	{
		.key = "log.tag.HandoverClient",
		.value = "INFO",
	},
	{
		.key = "log.tag.HandoverServer",
		.value = "INFO",
	},
	{
		.key = "log.tag.Handsfree",
		.value = "INFO",
	},
	{
		.key = "log.tag.IzatProviderBase",
		.value = "INFO",
	},
	{
		.key = "log.tag.IzatProviderEngine",
		.value = "INFO",
	},
	{
		.key = "log.tag.IzatServiceBase",
		.value = "INFO",
	},
	{
		.key = "log.tag.LocSvc_ApiV02",
		.value = "INFO",
	},
	{
		.key = "log.tag.LocSvc_EngAdapter",
		.value = "INFO",
	},
	{
		.key = "log.tag.LocSvc_LBSApiBase",
		.value = "INFO",
	},
	{
		.key = "log.tag.LocSvc_LBSApiV02",
		.value = "INFO",
	},
	{
		.key = "log.tag.LocSvc_LBSProxy",
		.value = "INFO",
	},
	{
		.key = "log.tag.LocSvc_LocUlpProxy",
		.value = "INFO",
	},
	{
		.key = "log.tag.LocSvc_NiH",
		.value = "INFO",
	},
	{
		.key = "log.tag.LocSvc_afw",
		.value = "INFO",
	},
	{
		.key = "log.tag.LocSvc_api_v02",
		.value = "INFO",
	},
	{
		.key = "log.tag.LocSvc_eng",
		.value = "INFO",
	},
	{
		.key = "log.tag.LocSvc_ext",
		.value = "INFO",
	},
	{
		.key = "log.tag.LocSvc_java",
		.value = "INFO",
	},
	{
		.key = "log.tag.LocSvc_jni",
		.value = "INFO",
	},
	{
		.key = "log.tag.LocSvc_libulp",
		.value = "INFO",
	},
	{
		.key = "log.tag.LocationManagerService",
		.value = "INFO",
	},
	{
		.key = "log.tag.NFC",
		.value = "INFO",
	},
	{
		.key = "log.tag.NetworkLocationProvider",
		.value = "INFO",
	},
	{
		.key = "log.tag.NetworkLocationService",
		.value = "INFO",
	},
	{
		.key = "log.tag.NfcDispatcher",
		.value = "INFO",
	},
	{
		.key = "log.tag.NfcHandover",
		.value = "INFO",
	},
	{
		.key = "log.tag.OsAgent",
		.value = "INFO",
	},
	{
		.key = "log.tag.SapRilReceiver",
		.value = "INFO",
	},
	{
		.key = "log.tag.SnepClient",
		.value = "INFO",
	},
	{
		.key = "log.tag.SnepMessenger",
		.value = "INFO",
	},
	{
		.key = "log.tag.SnepServer",
		.value = "INFO",
	},
	{
		.key = "log.tag.UnifiedLocationProvider",
		.value = "INFO",
	},
	{
		.key = "log.tag.UnifiedLocationService",
		.value = "INFO",
	},
	{
		.key = "media.aac_51_output_enabled",
		.value = "true",
	},
	{
		.key = "media.stagefright.audio.sink",
		.value = "280",
	},
	{
		.key = "media.stagefright.enable-aac",
		.value = "true",
	},
	{
		.key = "media.stagefright.enable-http",
		.value = "true",
	},
	{
		.key = "media.stagefright.enable-player",
		.value = "true",
	},
	{
		.key = "media.stagefright.enable-qcp",
		.value = "true",
	},
	{
		.key = "media.stagefright.enable-scan",
		.value = "true",
	},
	{
		.key = "mm.enable.qcom_parser",
		.value = "4177919",
	},
	{
		.key = "mm.enable.smoothstreaming",
		.value = "true",
	},
	{
		.key = "mmp.enable.3g2",
		.value = "true",
	},
	{
		.key = "net.bt.name",
		.value = "Android",
	},
	{
		.key = "net.change",
		.value = "net.dns2",
	},
	{
		.key = "net.dns1",
		.value = "208.67.222.222",
	},
	{
		.key = "net.dns2",
		.value = "208.67.220.220",
	},
	{
		.key = "net.hostname",
		.value = "android-5043742c1d40356a",
	},
	{
		.key = "net.lte.ims.data.enabled",
		.value = "true",
	},
	{
		.key = "net.qtaguid_enabled",
		.value = "1",
	},
	{
		.key = "net.tcp.2g_init_rwnd",
		.value = "10",
	},
	{
		.key = "net.tcp.buffersize.default",
		.value = "4096,87380,524288,4096,16384,110208",
	},
	{
		.key = "net.tcp.buffersize.edge",
		.value = "4093,26280,35040,4096,16384,35040",
	},
	{
		.key = "net.tcp.buffersize.evdo",
		.value = "4094,87380,524288,4096,16384,262144",
	},
	{
		.key = "net.tcp.buffersize.gprs",
		.value = "4092,8760,11680,4096,8760,11680",
	},
	{
		.key = "net.tcp.buffersize.hsdpa",
		.value = "4094,87380,1220608,4096,16384,1220608",
	},
	{
		.key = "net.tcp.buffersize.hspa",
		.value = "4094,87380,1220608,4096,16384,1220608",
	},
	{
		.key = "net.tcp.buffersize.hspap",
		.value = "4094,87380,1220608,4096,16384,1220608",
	},
	{
		.key = "net.tcp.buffersize.hsupa",
		.value = "4094,87380,1220608,4096,16384,1220608",
	},
	{
		.key = "net.tcp.buffersize.lte",
		.value = "2097152,4194304,8388608,262144,524288,1048576",
	},
	{
		.key = "net.tcp.buffersize.umts",
		.value = "4094,87380,110208,4096,16384,110208",
	},
	{
		.key = "net.tcp.buffersize.wifi",
		.value = "524288,2097152,4194304,262144,524288,1048576",
	},
	{
		.key = "net.tcp.default_init_rwnd",
		.value = "60",
	},
	{
		.key = "oem.device.imeicache",
		.value = "014836007332613",
	},
	{
		.key = "oplib.oneplus_sdk_utils",
		.value = "0.1.2",
	},
	{
		.key = "oplib.oneplus_sdk_wrapper",
		.value = "0.1.0",
	},
	{
		.key = "persist.audio.fluence.speaker",
		.value = "true",
	},
	{
		.key = "persist.audio.fluence.voicecall",
		.value = "true",
	},
	{
		.key = "persist.audio.fluence.voicerec",
		.value = "false",
	},
	{
		.key = "persist.camera.debug.logfile",
		.value = "0",
	},
	{
		.key = "persist.camera.gyro.disable",
		.value = "0",
	},
	{
		.key = "persist.camera.mobicat",
		.value = "2",
	},
	{
		.key = "persist.camera.stats.debugexif",
		.value = "3080192",
	},
	{
		.key = "persist.cne.feature",
		.value = "1",
	},
	{
		.key = "persist.data.df.agg.dl_pkt",
		.value = "10",
	},
	{
		.key = "persist.data.df.agg.dl_size",
		.value = "4096",
	},
	{
		.key = "persist.data.df.dev_name",
		.value = "rmnet_usb0",
	},
	{
		.key = "persist.data.df.dl_mode",
		.value = "5",
	},
	{
		.key = "persist.data.df.iwlan_mux",
		.value = "9",
	},
	{
		.key = "persist.data.df.mux_count",
		.value = "8",
	},
	{
		.key = "persist.data.df.ul_mode",
		.value = "5",
	},
	{
		.key = "persist.data.iwlan.enable",
		.value = "true",
	},
	{
		.key = "persist.data.mode",
		.value = "concurrent",
	},
	{
		.key = "persist.data.netmgrd.qos.enable",
		.value = "true",
	},
	{
		.key = "persist.data.wda.enable",
		.value = "true",
	},
	{
		.key = "persist.dbg.ims_volte_enable",
		.value = "0",
	},
	{
		.key = "persist.dbg.volte_avail_ovr",
		.value = "0",
	},
	{
		.key = "persist.dbg.vt_avail_ovr",
		.value = "0",
	},
	{
		.key = "persist.dbg.wfc_avail_ovr",
		.value = "0",
	},
	{
		.key = "persist.debug.coresight.config",
		.value = "stm-events",
	},
	{
		.key = "persist.debug.wfd.enable",
		.value = "1",
	},
	{
		.key = "persist.demo.hdmirotationlock",
		.value = "false",
	},
	{
		.key = "persist.dirac.acs.controller",
		.value = "qem",
	},
	{
		.key = "persist.dpm.feature",
		.value = "11",
	},
	{
		.key = "persist.fuse_sdcard",
		.value = "true",
	},
	{
		.key = "persist.hwc.enable_vds",
		.value = "1",
	},
	{
		.key = "persist.mm.enable.prefetch",
		.value = "true",
	},
	{
		.key = "persist.net.doxlat",
		.value = "true",
	},
	{
		.key = "persist.oem.dump",
		.value = "0",
	},
	{
		.key = "persist.qfp",
		.value = "false",
	},
	{
		.key = "persist.radio.adb_log_on",
		.value = "0",
	},
	{
		.key = "persist.radio.apm_sim_not_pwdn",
		.value = "1",
	},
	{
		.key = "persist.radio.apns_ver_xml",
		.value = "8",
	},
	{
		.key = "persist.radio.custom_ecc",
		.value = "1",
	},
	{
		.key = "persist.radio.data_ltd_sys_ind",
		.value = "1",
	},
	{
		.key = "persist.radio.enhance_ecall",
		.value = "true",
	},
	{
		.key = "persist.radio.eons.enabled",
		.value = "false",
	},
	{
		.key = "persist.radio.force_on_dc",
		.value = "true",
	},
	{
		.key = "persist.radio.hw_mbn_update",
		.value = "0",
	},
	{
		.key = "persist.radio.ignore_dom_time",
		.value = "10",
	},
	{
		.key = "persist.radio.logenable",
		.value = "false",
	},
	{
		.key = "persist.radio.msim.stackid_0",
		.value = "0",
	},
	{
		.key = "persist.radio.msim.stackid_1",
		.value = "1",
	},
	{
		.key = "persist.radio.multisim.config",
		.value = "dsds",
	},
	{
		.key = "persist.radio.rat_on",
		.value = "combine",
	},
	{
		.key = "persist.radio.ril_payload_on",
		.value = "0",
	},
	{
		.key = "persist.radio.sglte_target",
		.value = "0",
	},
	{
		.key = "persist.radio.sib16_support",
		.value = "1",
	},
	{
		.key = "persist.radio.stack_id_0",
		.value = "0",
	},
	{
		.key = "persist.radio.stack_id_1",
		.value = "1",
	},
	{
		.key = "persist.radio.start_ota_daemon",
		.value = "1",
	},
	{
		.key = "persist.radio.sw_mbn_loaded",
		.value = "1",
	},
	{
		.key = "persist.radio.sw_mbn_update",
		.value = "0",
	},
	{
		.key = "persist.rild.nitz_long_ons_0",
		.value = "",
	},
	{
		.key = "persist.rild.nitz_long_ons_1",
		.value = "",
	},
	{
		.key = "persist.rild.nitz_long_ons_2",
		.value = "",
	},
	{
		.key = "persist.rild.nitz_long_ons_3",
		.value = "",
	},
	{
		.key = "persist.rild.nitz_plmn",
		.value = "",
	},
	{
		.key = "persist.rild.nitz_short_ons_0",
		.value = "",
	},
	{
		.key = "persist.rild.nitz_short_ons_1",
		.value = "",
	},
	{
		.key = "persist.rild.nitz_short_ons_2",
		.value = "",
	},
	{
		.key = "persist.rild.nitz_short_ons_3",
		.value = "",
	},
	{
		.key = "persist.rmnet.data.enable",
		.value = "true",
	},
	{
		.key = "persist.service.bdroid.bdaddr",
		.value = "94:65:2d:2c:a9:42",
	},
	{
		.key = "persist.sys.911.shutdown",
		.value = "1",
	},
	{
		.key = "persist.sys.adb.engineermode",
		.value = "1",
	},
	{
		.key = "persist.sys.allcommode",
		.value = "false",
	},
	{
		.key = "persist.sys.assert.enable",
		.value = "false",
	},
	{
		.key = "persist.sys.assert.panic",
		.value = "false",
	},
	{
		.key = "persist.sys.bootloader",
		.value = "yes",
	},
	{
		.key = "persist.sys.cfu_auto",
		.value = "1",
	},
	{
		.key = "persist.sys.cnd.iwlan",
		.value = "1",
	},
	{
		.key = "persist.sys.crash",
		.value = "yes",
	},
	{
		.key = "persist.sys.dalvik.vm.lib.2",
		.value = "libart.so",
	},
	{
		.key = "persist.sys.density.mark",
		.value = "480",
	},
	{
		.key = "persist.sys.device_first_boot",
		.value = "0",
	},
	{
		.key = "persist.sys.diag.max.size",
		.value = "200",
	},
	{
		.key = "persist.sys.dpmd.tcm",
		.value = "2",
	},
	{
		.key = "persist.sys.event",
		.value = "yes",
	},
	{
		.key = "persist.sys.idle.soff",
		.value = "19,63358",
	},
	{
		.key = "persist.sys.kernel",
		.value = "yes",
	},
	{
		.key = "persist.sys.locale",
		.value = "en-US",
	},
	{
		.key = "persist.sys.main",
		.value = "yes",
	},
	{
		.key = "persist.sys.oem.region",
		.value = "OverSeas",
	},
	{
		.key = "persist.sys.oem_smooth",
		.value = "1",
	},
	{
		.key = "persist.sys.pd_enable",
		.value = "0",
	},
	{
		.key = "persist.sys.pre_bootloader",
		.value = "yes",
	},
	{
		.key = "persist.sys.profiler_ms",
		.value = "0",
	},
	{
		.key = "persist.sys.qsee",
		.value = "yes",
	},
	{
		.key = "persist.sys.qxdm",
		.value = "no",
	},
	{
		.key = "persist.sys.radio",
		.value = "yes",
	},
	{
		.key = "persist.sys.system",
		.value = "yes",
	},
	{
		.key = "persist.sys.timezone",
		.value = "America/New_York",
	},
	{
		.key = "persist.sys.tz",
		.value = "yes",
	},
	{
		.key = "persist.sys.usb.config",
		.value = "mtp,adb",
	},
	{
		.key = "persist.sys.usb.config.extra",
		.value = "none",
	},
	{
		.key = "persist.sys.version.lastota",
		.value = "OnePlus3TOxygen_28.A.41_GLO_041_1702081824",
	},
	{
		.key = "persist.sys.version.ota",
		.value = "OnePlus3TOxygen_28.A.57_GLO_057_1710122300",
	},
	{
		.key = "persist.sys.webview.vmsize",
		.value = "112887376",
	},
	{
		.key = "persist.sys.wfd.virtual",
		.value = "0",
	},
	{
		.key = "persist.timed.enable",
		.value = "true",
	},
	{
		.key = "persist.ts.postmakeup",
		.value = "false",
	},
	{
		.key = "persist.ts.rtmakeup",
		.value = "false",
	},
	{
		.key = "persist.volte_enalbed_by_hw",
		.value = "1",
	},
	{
		.key = "pm.dexopt.ab-ota",
		.value = "speed-profile",
	},
	{
		.key = "pm.dexopt.bg-dexopt",
		.value = "speed-profile",
	},
	{
		.key = "pm.dexopt.boot",
		.value = "verify-profile",
	},
	{
		.key = "pm.dexopt.core-app",
		.value = "speed",
	},
	{
		.key = "pm.dexopt.first-boot",
		.value = "interpret-only",
	},
	{
		.key = "pm.dexopt.forced-dexopt",
		.value = "speed",
	},
	{
		.key = "pm.dexopt.install",
		.value = "interpret-only",
	},
	{
		.key = "pm.dexopt.nsys-library",
		.value = "speed",
	},
	{
		.key = "pm.dexopt.shared-apk",
		.value = "speed",
	},
	{
		.key = "qcom.bluetooth.soc",
		.value = "rome",
	},
	{
		.key = "qcom.hw.aac.encoder",
		.value = "true",
	},
	{
		.key = "qemu.hw.mainkeys",
		.value = "1",
	},
	{
		.key = "ril.ecclist",
		.value = "*911,#911,000,08,110,999,118,119,120,122,911,112",
	},
	{
		.key = "ril.ecclist1",
		.value = "*911,#911,000,08,110,999,118,119,120,122,911,112",
	},
	{
		.key = "ril.qcril_pre_init_lock_held",
		.value = "0",
	},
	{
		.key = "ril.subscription.types",
		.value = "NV,RUIM",
	},
	{
		.key = "rild.libpath",
		.value = "/vendor/lib64/libril-qc-qmi-1.so",
	},
	{
		.key = "ro.adb.secure",
		.value = "1",
	},
	{
		.key = "ro.alarm_boot",
		.value = "false",
	},
	{
		.key = "ro.allow.mock.location",
		.value = "0",
	},
	{
		.key = "ro.am.reschedule_service",
		.value = "true",
	},
	{
		.key = "ro.baseband",
		.value = "msm",
	},
	{
		.key = "ro.bluetooth.dun",
		.value = "true",
	},
	{
		.key = "ro.bluetooth.emb_wp_mode",
		.value = "true",
	},
	{
		.key = "ro.bluetooth.hfp.ver",
		.value = "1.7",
	},
	{
		.key = "ro.bluetooth.sap",
		.value = "true",
	},
	{
		.key = "ro.bluetooth.wipower",
		.value = "true",
	},
	{
		.key = "ro.board.platform",
		.value = "msm8996",
	},
	{
		.key = "ro.boot.angela",
		.value = "disabled",
	},
	{
		.key = "ro.boot.authorized_kernel",
		.value = "true",
	},
	{
		.key = "ro.boot.baseband",
		.value = "msm",
	},
	{
		.key = "ro.boot.bootdevice",
		.value = "624000.ufshc",
	},
	{
		.key = "ro.boot.enable_dm_verity",
		.value = "1",
	},
	{
		.key = "ro.boot.hardware",
		.value = "qcom",
	},
	{
		.key = "ro.boot.hw_version",
		.value = "28",
	},
	{
		.key = "ro.boot.keymaster",
		.value = "1",
	},
	{
		.key = "ro.boot.mode",
		.value = "reboot",
	},
	{
		.key = "ro.boot.nobatt",
		.value = "0",
	},
	{
		.key = "ro.boot.pcba_number",
		.value = "001581307202032000002417",
	},
	{
		.key = "ro.boot.project_name",
		.value = "15811",
	},
	{
		.key = "ro.boot.rf_version",
		.value = "32",
	},
	{
		.key = "ro.boot.rpmb_enable",
		.value = "true",
	},
	{
		.key = "ro.boot.secboot",
		.value = "enabled",
	},
	{
		.key = "ro.boot.serialno",
		.value = "e20c8fc0",
	},
	{
		.key = "ro.boot.verifiedbootstate",
		.value = "green",
	},
	{
		.key = "ro.boot.veritymode",
		.value = "enforcing",
	},
	{
		.key = "ro.bootimage.build.date",
		.value = "Thu Oct 12 22:53:06 CST 2017",
	},
	{
		.key = "ro.bootimage.build.date.utc",
		.value = "1507819986",
	},
	{
		.key = "ro.bootimage.build.fingerprint",
		.value = "OnePlus/OnePlus3/OnePlus3T:7.1.1/NMF26F/10122113:user/release-keys",
	},
	{
		.key = "ro.bootloader",
		.value = "unknown",
	},
	{
		.key = "ro.bootmode",
		.value = "reboot",
	},
	{
		.key = "ro.build.characteristics",
		.value = "nosdcard",
	},
	{
		.key = "ro.build.date",
		.value = "Thu Oct 12 22:53:06 CST 2017",
	},
	{
		.key = "ro.build.date.Ymd",
		.value = "171012",
	},
	{
		.key = "ro.build.date.YmdHM",
		.value = "201710122300",
	},
	{
		.key = "ro.build.date.utc",
		.value = "1507819986",
	},
	{
		.key = "ro.build.date.ymd",
		.value = "171012",
	},
	{
		.key = "ro.build.description",
		.value = "OnePlus3-user 7.1.1 NMF26F 136 dev-keys",
	},
	{
		.key = "ro.build.display.full_id",
		.value = "ONEPLUS A3000_28_A.57_171012",
	},
	{
		.key = "ro.build.display.id",
		.value = "ONEPLUS A3000_28_171012",
	},
	{
		.key = "ro.build.fingerprint",
		.value = "OnePlus/OnePlus3/OnePlus3T:7.1.1/NMF26F/10122113:user/release-keys",
	},
	{
		.key = "ro.build.flavor",
		.value = "OnePlus3-user",
	},
	{
		.key = "ro.build.host",
		.value = "ubuntu-64",
	},
	{
		.key = "ro.build.id",
		.value = "NMF26F",
	},
	{
		.key = "ro.build.id.hardware",
		.value = "ONEPLUS A3000_28_",
	},
	{
		.key = "ro.build.kernel.id",
		.value = "3.18-G1710122300",
	},
	{
		.key = "ro.build.oemfingerprint",
		.value = "7.1.1/NMF26F/10122113:user/release-keys",
	},
	{
		.key = "ro.build.ota.versionname",
		.value = "OnePlus3TOxygen_28_1710122300",
	},
	{
		.key = "ro.build.product",
		.value = "OnePlus3",
	},
	{
		.key = "ro.build.release_type",
		.value = "release",
	},
	{
		.key = "ro.build.soft.majorversion",
		.value = "A",
	},
	{
		.key = "ro.build.soft.version",
		.value = "A.57",
	},
	{
		.key = "ro.build.tags",
		.value = "release-keys",
	},
	{
		.key = "ro.build.type",
		.value = "user",
	},
	{
		.key = "ro.build.user",
		.value = "OnePlus",
	},
	{
		.key = "ro.build.version.all_codenames",
		.value = "REL",
	},
	{
		.key = "ro.build.version.base_os",
		.value = "",
	},
	{
		.key = "ro.build.version.codename",
		.value = "REL",
	},
	{
		.key = "ro.build.version.incremental",
		.value = "136",
	},
	{
		.key = "ro.build.version.ota",
		.value = "OnePlus3TOxygen_28.A.57_GLO_057_1710122300",
	},
	{
		.key = "ro.build.version.preview_sdk",
		.value = "0",
	},
	{
		.key = "ro.build.version.release",
		.value = "7.1.1",
	},
	{
		.key = "ro.build.version.sdk",
		.value = "25",
	},
	{
		.key = "ro.build.version.security_patch",
		.value = "2017-08-01",
	},
	{
		.key = "ro.carrier",
		.value = "unknown",
	},
	{
		.key = "ro.com.android.dataroaming",
		.value = "false",
	},
	{
		.key = "ro.com.google.gmsversion",
		.value = "7.1_r4",
	},
	{
		.key = "ro.common.soft",
		.value = "OnePlus3",
	},
	{
		.key = "ro.config.alarm_alert",
		.value = "spring.ogg",
	},
	{
		.key = "ro.config.mms_notification",
		.value = "free.ogg",
	},
	{
		.key = "ro.config.notification_sound",
		.value = "meet.ogg",
	},
	{
		.key = "ro.config.ringtone",
		.value = "oneplus_tune.ogg",
	},
	{
		.key = "ro.crypto.fs_crypto_blkdev",
		.value = "/dev/block/dm-1",
	},
	{
		.key = "ro.crypto.state",
		.value = "encrypted",
	},
	{
		.key = "ro.crypto.type",
		.value = "block",
	},
	{
		.key = "ro.cutoff_voltage_mv",
		.value = "3250",
	},
	{
		.key = "ro.dalvik.vm.native.bridge",
		.value = "0",
	},
	{
		.key = "ro.debuggable",
		.value = "0",
	},
	{
		.key = "ro.display.series",
		.value = "OnePlus 3T",
	},
	{
		.key = "ro.expect.recovery_id",
		.value = "0x38e644b768c30cbec99fead9e0b227c97264a49f000000000000000000000000",
	},
	{
		.key = "ro.frp.pst",
		.value = "/dev/block/bootdevice/by-name/config",
	},
	{
		.key = "ro.gpu.available_frequencies",
		.value = "652800000 624000000 560000000 510000000 401800000 315000000 214000000 133000000 ",
	},
	{
		.key = "ro.hardware",
		.value = "qcom",
	},
	{
		.key = "ro.hwui.drop_shadow_cache_size",
		.value = "7",
	},
	{
		.key = "ro.hwui.gradient_cache_size",
		.value = "1",
	},
	{
		.key = "ro.hwui.layer_cache_size",
		.value = "64",
	},
	{
		.key = "ro.hwui.path_cache_size",
		.value = "39",
	},
	{
		.key = "ro.hwui.r_buffer_cache_size",
		.value = "12",
	},
	{
		.key = "ro.hwui.text_large_cache_height",
		.value = "2048",
	},
	{
		.key = "ro.hwui.text_large_cache_width",
		.value = "3072",
	},
	{
		.key = "ro.hwui.text_small_cache_height",
		.value = "2048",
	},
	{
		.key = "ro.hwui.text_small_cache_width",
		.value = "2048",
	},
	{
		.key = "ro.hwui.texture_cache_flushrate",
		.value = "0.4",
	},
	{
		.key = "ro.hwui.texture_cache_size",
		.value = "96",
	},
	{
		.key = "ro.logdumpd.enabled",
		.value = "0",
	},
	{
		.key = "ro.mdtp.package_name2",
		.value = "com.qualcomm.qti.securemsm.mdtp.MdtpDemo",
	},
	{
		.key = "ro.nfc.port",
		.value = "I2C",
	},
	{
		.key = "ro.opengles.version",
		.value = "196610",
	},
	{
		.key = "ro.oxygen.version",
		.value = "4.5.1",
	},
	{
		.key = "ro.product.board",
		.value = "QC_Reference_Phone",
	},
	{
		.key = "ro.product.brand",
		.value = "OnePlus",
	},
	{
		.key = "ro.product.cpu.abi",
		.value = "arm64-v8a",
	},
	{
		.key = "ro.product.cpu.abilist",
		.value = "arm64-v8a,armeabi-v7a,armeabi",
	},
	{
		.key = "ro.product.cpu.abilist32",
		.value = "armeabi-v7a,armeabi",
	},
	{
		.key = "ro.product.cpu.abilist64",
		.value = "arm64-v8a",
	},
	{
		.key = "ro.product.device",
		.value = "OnePlus3T",
	},
	{
		.key = "ro.product.first_api_level",
		.value = "23",
	},
	{
		.key = "ro.product.locale",
		.value = "en-US",
	},
	{
		.key = "ro.product.manufacturer",
		.value = "OnePlus",
	},
	{
		.key = "ro.product.model",
		.value = "ONEPLUS A3000",
	},
	{
		.key = "ro.product.name",
		.value = "OnePlus3",
	},
	{
		.key = "ro.qc.sdk.audio.fluencetype",
		.value = "fluence",
	},
	{
		.key = "ro.qc.sdk.audio.ssr",
		.value = "false",
	},
	{
		.key = "ro.qc.sdk.us.proximity",
		.value = "1",
	},
	{
		.key = "ro.qti.sensors.dev_ori",
		.value = "false",
	},
	{
		.key = "ro.qti.sensors.mot_detect",
		.value = "false",
	},
	{
		.key = "ro.qti.sensors.pmd",
		.value = "false",
	},
	{
		.key = "ro.qti.sensors.sta_detect",
		.value = "false",
	},
	{
		.key = "ro.qualcomm.bluetooth.ftp",
		.value = "true",
	},
	{
		.key = "ro.qualcomm.bluetooth.hfp",
		.value = "true",
	},
	{
		.key = "ro.qualcomm.bluetooth.hsp",
		.value = "true",
	},
	{
		.key = "ro.qualcomm.bluetooth.map",
		.value = "true",
	},
	{
		.key = "ro.qualcomm.bluetooth.nap",
		.value = "true",
	},
	{
		.key = "ro.qualcomm.bluetooth.opp",
		.value = "true",
	},
	{
		.key = "ro.qualcomm.bluetooth.pbap",
		.value = "true",
	},
	{
		.key = "ro.qualcomm.cabl",
		.value = "0",
	},
	{
		.key = "ro.remount.time",
		.value = "0",
	},
	{
		.key = "ro.revision",
		.value = "0",
	},
	{
		.key = "ro.rf_version",
		.value = "TDD_FDD_Am",
	},
	{
		.key = "ro.ril.supportLTE",
		.value = "1",
	},
	{
		.key = "ro.ril.svdo",
		.value = "false",
	},
	{
		.key = "ro.ril.svlte1x",
		.value = "false",
	},
	{
		.key = "ro.runtime.firstboot",
		.value = "1520013281463",
	},
	{
		.key = "ro.secure",
		.value = "1",
	},
	{
		.key = "ro.serialno",
		.value = "e20c8fc0",
	},
	{
		.key = "ro.setupwizard.mode",
		.value = "OPTIONAL",
	},
	{
		.key = "ro.sf.lcd_density",
		.value = "420",
	},
	{
		.key = "ro.sys.fw.bg_apps_limit",
		.value = "32",
	},
	{
		.key = "ro.sys.sdcardfs",
		.value = "true",
	},
	{
		.key = "ro.telephony.call_ring.multiple",
		.value = "false",
	},
	{
		.key = "ro.telephony.default_network",
		.value = "22",
	},
	{
		.key = "ro.use_data_netmgrd",
		.value = "true",
	},
	{
		.key = "ro.vendor.at_library",
		.value = "libqti-at.so",
	},
	{
		.key = "ro.vendor.extension_library",
		.value = "libqti-perfd-client.so",
	},
	{
		.key = "ro.vendor.gt_library",
		.value = "libqti-gt.so",
	},
	{
		.key = "ro.vendor.wl_library",
		.value = "libqti-wl.so",
	},
	{
		.key = "ro.wifi.channels",
		.value = "",
	},
	{
		.key = "ro.xxversion",
		.value = "v0.5",
	},
	{
		.key = "ro.zygote",
		.value = "zygote64_32",
	},
	{
		.key = "sdm.debug.disable_rotator_split",
		.value = "1",
	},
	{
		.key = "sdm.perf_hint_window",
		.value = "50",
	},
	{
		.key = "security.perf_harden",
		.value = "1",
	},
	{
		.key = "service.bootanim.exit",
		.value = "1",
	},
	{
		.key = "sys.boot_completed",
		.value = "1",
	},
	{
		.key = "sys.cgroup.active",
		.value = "0",
	},
	{
		.key = "sys.cgroup.version",
		.value = "v15112601",
	},
	{
		.key = "sys.games.gt.prof",
		.value = "1",
	},
	{
		.key = "sys.ims.QMI_DAEMON_STATUS",
		.value = "1",
	},
	{
		.key = "sys.keymaster.loaded",
		.value = "true",
	},
	{
		.key = "sys.listeners.registered",
		.value = "true",
	},
	{
		.key = "sys.normalcount",
		.value = "true",
	},
	{
		.key = "sys.oem_unlock_allowed",
		.value = "0",
	},
	{
		.key = "sys.post_boot.parsed",
		.value = "1",
	},
	{
		.key = "sys.srgb",
		.value = "0",
	},
	{
		.key = "sys.sysctl.extra_free_kbytes",
		.value = "24300",
	},
	{
		.key = "sys.sysctl.tcp_def_init_rwnd",
		.value = "60",
	},
	{
		.key = "sys.trigger_resize",
		.value = "0",
	},
	{
		.key = "sys.usb.cdrom",
		.value = "/system/etc/usb_drivers.iso",
	},
	{
		.key = "sys.usb.config",
		.value = "mtp,adb",
	},
	{
		.key = "sys.usb.ffs.ready",
		.value = "1",
	},
	{
		.key = "sys.usb.rndis.func.name",
		.value = "rndis_bam",
	},
	{
		.key = "sys.usb.rps_mask",
		.value = "0",
	},
	{
		.key = "sys.usb.state",
		.value = "mtp,adb",
	},
	{
		.key = "telephony.lteOnCdmaDevice",
		.value = "1,1",
	},
	{
		.key = "tunnel.audio.encode",
		.value = "false",
	},
	{
		.key = "use.qti.sw.alac.decoder",
		.value = "true",
	},
	{
		.key = "use.qti.sw.ape.decoder",
		.value = "true",
	},
	{
		.key = "use.voice.path.for.pcm.voip",
		.value = "true",
	},
	{
		.key = "vidc.debug.perf.mode",
		.value = "2",
	},
	{
		.key = "vidc.enc.dcvs.extra-buff-count",
		.value = "2",
	},
	{
		.key = "vidc.enc.disable.pq",
		.value = "true",
	},
	{
		.key = "vold.datafs.type",
		.value = "F2FS",
	},
	{
		.key = "vold.decrypt",
		.value = "trigger_restart_framework",
	},
	{
		.key = "vold.has_adoptable",
		.value = "0",
	},
	{
		.key = "vold.internalSD.mount",
		.value = "1",
	},
	{
		.key = "vold.post_fs_data_done",
		.value = "1",
	},
	{
		.key = "wifi.interface",
		.value = "wlan0",
	},
	{
		.key = "wlan.driver.status",
		.value = "ok",
	},
	{ NULL },
};
#endif /* __ANDROID__ */
